var English = {};

English.Lesson1 = {
    LessonType : 'eng',
    Name : 'Lesson 1',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"answer":"Get in touch with", "title":"поддерживать отношения с", synonyms:[]},
        {"answer":"What kind", "title":"какой тип", synonyms:[]},
        {"answer":"above", "title":"выше", synonyms:[]},
        {"answer":"accordingly", "title":"соответственно", synonyms:[]},
        {"answer":"actually", "title":"на самом деле", synonyms:[]},
        {"answer":"advantage", "title":"преимущество", synonyms:[]},
        {"answer":"advertising", "title":"реклама", synonyms:[]},
        {"answer":"affectionate", "title":"слишком привязанный", synonyms:[]},
        {"answer":"afterwards",  "title":"в конце концов", synonyms:[]},
        {"answer":"although", "title":"хотя", synonyms:[]},
        {"answer":"anthem", "title":"гимн", synonyms:[]},
        {"answer":"anyway", "title":"так или иначе, в любом случаe", synonyms:[]},
        {"answer":"argue", "title":"спорить", synonyms:[]},
        {"answer":"arrange", "title":"организовывать", synonyms:[]},
        {"answer":"asleep", "title":"спящий", synonyms:[]},
        {"answer":"at the same", "title":"тоже самое", synonyms:[]},
        {"answer":"auxiliary", "title":"вспомогательный", synonyms:[]},
        {"answer":"avalanche", "title":"лавина", synonyms:[]},
        {"answer":"bad language", "title":"сквернословие", synonyms:[]},
        {"answer":"basement", "title":"подвал", synonyms:[]},
        {"answer":"belong", "title":"принадлежать", synonyms:[]},
        {"answer":"below", "title":"ниже", synonyms:[]},
        {"answer":"bet", "title":"уверять", "title":"быть уверенным на все сто", synonyms:[]},
        {"answer":"bless you", "title":"будь здоров", synonyms:[]},
        {"answer":"bone", "title":"кость", synonyms:[]},
        {"answer":"boring", "title":"скучный", synonyms:[]},
        {"answer":"borrow", "title":"давать в долг", synonyms:[]},
        {"answer":"breeding", "title":"пассатижи", synonyms:[]},
        {"answer":"brilliant", "title":"восхитительно", synonyms:[]},
        {"answer":"buckwheat porridge", "title":"гречневая каша", synonyms:[]},
        {"answer":"calmly", "title":"спокойно", synonyms:[]},
        {"answer":"carefully", "title":"осторожно", synonyms:[]},
        {"answer":"carpet", "title":"ковер", synonyms:[]},
        {"answer":"carry on", "title":"продолжать", synonyms:[]},
        {"answer":"classmates", "title":"одноклассники", synonyms:[]},
        {"answer":"clever", "title":"умный", synonyms:[]},
        {"answer":"climber", "title":"скалолаз", synonyms:[]},
        {"answer":"comma", "title":"запятая", synonyms:[]},
        {"answer":"commute", "title":"ездить", "title":"регулярно ездить", synonyms:[]},
        {"answer":"compete", "title":"соревноваться", synonyms:[]},
        {"answer":"competition", "title":"соревнование", synonyms:[]},
        {"answer":"competitive", "title":"соревновательный", synonyms:[]},
        {"answer":"completely", "title":"полностью", synonyms:[]},
        {"answer":"confidence", "title":"уверенность в себе", synonyms:[]},
        {"answer":"console", "title":"принимать решение", synonyms:[]},
        {"answer":"consolidation", "title":"решение", "title":"принятие решения", synonyms:[]},
        {"answer":"conversation", "title":"разговор", synonyms:[]},
        {"answer":"couple", "title":"пара", synonyms:[]},
        {"answer":"cross off", "title":"вычеркнуть", synonyms:[]},
        {"answer":"curious", "title":"заинтересованный", synonyms:[]},
        {"answer":"cycling", "title":"езда на велосипеде", synonyms:[]},
        {"answer":"decide", "title":"решать", "title":"решать задачу", synonyms:[]},
        {"answer":"definitely", "title":"определенно", synonyms:[]},
        {"answer":"desert", "title":"пустыня", synonyms:[]},
        {"answer":"dinner", "title":"обед", synonyms:[]},
        {"answer":"disaster", "title":"кошмарная ситуация", synonyms:[]},
        {"answer":"divorced", "title":"разведенный", synonyms:[]},
        {"answer":"drill", "title":"дрель", synonyms:[]},
        {"answer":"dull", "title":"очень скучный", synonyms:[]},
        {"answer":"earn", "title":"зарабатывать", synonyms:[]},
        {"answer":"either", "title":"любой", synonyms:[]},
        {"answer":"enrolment", "title":"регистрация", synonyms:[]},
        {"answer":"even", "title":"даже", synonyms:[]},
        {"answer":"experience", "title":"опыт", synonyms:[]},
        {"answer":"explain", "title":"раскрывать", synonyms:[]},
        {"answer":"fancy", "title":"маскарад", synonyms:[]},
        {"answer":"fed up", "title":"доставать кого-то", synonyms:[]},
        {"answer":"feel like", "title":"быть склонным", "title":"хотеть сделать", synonyms:[]},
        {"answer":"find out", "title":"искать информацию", synonyms:[]},
        {"answer":"floor", "title":"пол", synonyms:[]},
        {"answer":"frighten", "title":"пугать", synonyms:[]},
        {"answer":"gates", "title":"забор", synonyms:[]},
        {"answer":"generous", "title":"щедрый", synonyms:[]},
        {"answer":"get engaged", "title":"быть помолвленным", synonyms:[]},
        {"answer":"get off", "title":"выйти из", synonyms:[]},
        {"answer":"get on well", "title":"быть в хороших отношениях", synonyms:[]},
        {"answer":"gloves", "title":"перчатки", synonyms:[]},
        {"answer":"gossip", "title":"сплетни", synonyms:[]},
        {"answer":"got the sack", "title":"потерять работу", synonyms:[]},
        {"answer":"grow", "title":"расти", synonyms:[]},
        {"answer":"habit", "title":"привычка", synonyms:[]},
        {"answer":"halves", "title":"половины", synonyms:[]},
        {"answer":"hang out with", "title":"проводить время с", synonyms:[]},
        {"answer":"have a time off", "title":"выходной, иметь свободное время", synonyms:[]},
        {"answer":"headache", "title":"головная боль", synonyms:[]},
        {"answer":"hire", "title":"нанимать", synonyms:[]},
        {"answer":"hood", "title":"капюшон", synonyms:[]},
        {"answer":"housewife", "title":"домохозяйка", synonyms:[]},
        {"answer":"huge", "title":"огромный", synonyms:[]},
        {"answer":"hurt", "title":"ранить", synonyms:[]},
        {"answer":"husband", "title":"муж", synonyms:[]},
        {"answer":"improve", "title":"улучшать", synonyms:[]},
        {"answer":"independent", "title":"независимый", synonyms:[]},
        {"answer":"infants", "title":"молодёжь", synonyms:[]},
        {"answer":"injure", "title":"повреждать", synonyms:[]},
        {"answer":"insurance", "title":"страхование", synonyms:[]},
        {"answer":"invent", "title":"изобретать", synonyms:[]},
        {"answer":"invite", "title":"приглашать", synonyms:[]},
        {"answer":"involve", "title":"включать", "title":"включать в себя", synonyms:[]},
        {"answer":"journey", "title":"поездка", synonyms:[]},
        {"answer":"laugh", "title":"смеяться", synonyms:[]},
        {"answer":"lawyer", "title":"адвокат", synonyms:[]},
        {"answer":"lazy", "title":"ленивый", synonyms:[]},
        {"answer":"log", "title":"бревно", synonyms:[]},
        {"answer":"look like", "title":"выглядеть похожим", synonyms:[]},
        {"answer":"look up", "title":"находить", synonyms:[]},
        {"answer":"loudly", "title":"громко", synonyms:[]},
        {"answer":"lunch", "title":"ланч", synonyms:[]},
        {"answer":"magnificent", "title":"лучше всего", synonyms:[]},
        {"answer":"marine", "title":"морской", synonyms:[]},
        {"answer":"marvelous", "title":"поразительно", synonyms:[]},
        {"answer":"mate", "title":"приятель", synonyms:[]},
        {"answer":"matter", "title":"иметь значение", "title":"значить", synonyms:[]},
        {"answer":"meal", "title":"еда", synonyms:[]},
        {"answer":"mean", "title":"скупой", synonyms:[]},
        {"answer":"mention", "title":"упоминание", synonyms:[]},
        {"answer":"millet porridge", "title":"пшенная каша", synonyms:[]},
        {"answer":"mittens", "title":"варежки", synonyms:[]},
        {"answer":"more expensive", "title":"более дорогой", synonyms:[]},
        {"answer":"mother tongue", "title":"родной язык", synonyms:[]},
        {"answer":"much cheaper", "title":"более дешевый", synonyms:[]},
        {"answer":"mustache", "title":"усы", synonyms:[]},
        {"answer":"nasty", "title":"противный", synonyms:[]},
        {"answer":"nerd", "title":"придурок", synonyms:[]},
        {"answer":"next to", "title":"рядом с", synonyms:[]},
        {"answer":"oatmeal porridge", "title":"овсяная каша", synonyms:[]},
        {"answer":"occasionally", "title":"иногда, время от времени", synonyms:[]},
        {"answer":"odd", "title":"странный", synonyms:[]},
        {"answer":"on a date", "title":"на свидании", synonyms:[]},
        {"answer":"on foot", "title":"пешком", synonyms:[]},
        {"answer":"opportunity", "title":"возможность, удобный случай", synonyms:[]},
        {"answer":"outstanding", "title":"выдающийся", synonyms:[]},
        {"answer":"overstressed", "title":"перенапрячься, быть перенапряженным", synonyms:[]},
        {"answer":"overweight", "title":"жирный", synonyms:[]},
        {"answer":"personal traits", "title":"черты характера", synonyms:[]},
        {"answer":"plumber", "title":"водопроводчик", synonyms:[]},
        {"answer":"polite", "title":"вежливый", synonyms:[]},
        {"answer":"pool", "title":"лужа", synonyms:[]},
        {"answer":"possibility", "title":"возможность, вероятность что случится", synonyms:[]},
        {"answer":"prefer", "title":"предпочитать", synonyms:[]},
        {"answer":"pretended to", "title":"притворялся", synonyms:[]}, 
        {"answer":"pretty", "title":"довольно", synonyms:[]},
        {"answer":"probably", "title":"вероятно", synonyms:[]},
        {"answer":"quiet", "title":"тихий", synonyms:[]},
        {"answer":"quite", "title":"довольно", synonyms:[]},
        {"answer":"rate", "title":"ставка", synonyms:[]},
        {"answer":"recently", "title":"недавно", synonyms:[]},
        {"answer":"recognize", "title":"признавать", synonyms:[]},
        {"answer":"reward", "title":"награда", synonyms:[]},
        {"answer":"rob", "title":"грабить", synonyms:[]},
        {"answer":"sail", "title":"плавать на чём то", synonyms:[]},
        {"answer":"sand", "title":"песок", synonyms:[]},
        {"answer":"scream", "title":"кричать", synonyms:[]},
        {"answer":"screwdriver", "title":"отвёртка", synonyms:[]},
        {"answer":"seem", "title":"выглядеть", synonyms:[]},
        {"answer":"selfish", "title":"самовлюбленность", synonyms:[]},
        {"answer":"shine", "title":"светить", synonyms:[]},
        {"answer":"shy", "title":"стеснительный", synonyms:[]},
        {"answer":"sight", "title":"взгляд", synonyms:[]},
        {"answer":"sightseeing", "title":"осмотр достопримечательностей", synonyms:[]},
        {"answer":"sitcom", "title":"ситуативная комедия", synonyms:[]},
        {"answer":"skiing", "title":"катание на лыжах", synonyms:[]},
        {"answer":"spoilt", "title":"испорченный", "title":"избалованный", synonyms:[]},
        {"answer":"stamp", "title":"марка", synonyms:[]},
        {"answer":"stay in touch", "title":"оставаться в отношениях", "title":"оставаться на связи", synonyms:[]},
        {"answer":"strong", "title":"сильный", synonyms:[]},
        {"answer":"supper", "title":"ужин", synonyms:[]},
        {"answer":"supply", "title":"снабжать", synonyms:[]},
        {"answer":"swallow", "title":"глотать", synonyms:[]},
        {"answer":"syllables", "title":"слоги", synonyms:[]},
        {"answer":"t-shirt", "title":"футболка", synonyms:[]},
        {"answer":"take a nap", "title":"вздремнуть", synonyms:[]},
        {"answer":"tall", "title":"высокий", synonyms:[]},
        {"answer":"taste", "title":"вкусный", synonyms:[]},
        {"answer":"terrible", "title":"ужасно", synonyms:[]},
        {"answer":"thin", "title":"худой", synonyms:[]},
        {"answer":"tie", "title":"галстук", synonyms:[]},
        {"answer":"tights", "title":"колготки", synonyms:[]},
        {"answer":"tire", "title":"устать", synonyms:[]},
        {"answer":"to be like", "title":"быть похожим по характеру", synonyms:[]},
        {"answer":"top", "title":"топ", synonyms:[]},
        {"answer":"track suit", "title":"спортивный костюм", synonyms:[]},
        {"answer":"trainers", "title":"кроссовки", synonyms:[]},
        {"answer":"trousers", "title":"брюки", synonyms:[]},
        {"answer":"up comma", "title":"верхняя запятая", synonyms:[]},
        {"answer":"vase", "title":"ваза", synonyms:[]},
        {"answer":"violence", "title":"насилие", synonyms:[]},
        {"answer":"waterfront", "title":"выезд к воде", synonyms:[]},
        {"answer":"weary", "title":"утомлять", synonyms:[]},
        {"answer":"whatever", "title":"что бы ни", synonyms:[]},
        {"answer":"wonder", "title":"интересно", synonyms:[]},
        {"answer":"wonderful", "title":"удивительно", synonyms:[]},
        {"answer":"worse", "title":"хуже", synonyms:[]},
        {"answer":"zealous", "title":"ревностный", synonyms:[]},
        {"answer":"jealous", "title":"ревнивый", synonyms:[]}, 
    
    ]
}

English.Lesson2 = {
    LessonType : 'eng',
    Name : 'Lesson 2',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"answer":"abroad", "title":	"заграница", synonyms:[]},	 
        {"answer":"accommodation", "title":	"расположение", synonyms:[]},	
        {"answer":"admire", "title":	"восхищаться", synonyms:[]},	
        {"answer":"adventure", "title":	"приключение", synonyms:[]},	 
        {"answer":"against", "title":	"против", synonyms:[]},	
        {"answer":"amazed", "title":	"быть впечатленным", synonyms:[]},	
        {"answer":"apparently", "title":	"по всей видимости", synonyms:[]},	
        {"answer":"awful", "title":	"ужасный", synonyms:[]},	
        {"answer":"bill", "title":	"счет", synonyms:[]},	
        {"answer":"billionaire", "title":	"миллиардер", synonyms:[]},	
        {"answer":"bless you", "title":	"будь здоров", synonyms:[]},	
        {"answer":"brave", "title":	"храбрость", synonyms:[]},	
        {"answer":"bravery", "title":	"храбрый", synonyms:[]},	
        {"answer":"cabbage", "title":	"капуста", synonyms:[]},	
        {"answer":"cake", "title":	"кекс", synonyms:[]},	
        {"answer":"campus", "title":	"общежитие", synonyms:[]},	
        {"answer":"cancer", "title":	"рак", synonyms:[]},	
        {"answer":"care of", "title":	"заботиться о", synonyms:[]},	
        {"answer":"caught a cold", "title":	"простудиться", synonyms:[]},	
        {"answer":"chest", "title":	"клад", synonyms:[]},	
        {"answer":"close people", "title":	"близкие люди", synonyms:[]},	
        {"answer":"clues", "title":	"доказательства", synonyms:[]},	
        {"answer":"coach", "title":	"автобус", synonyms:[]},	
        {"answer":"coast", "title":	"побережье", synonyms:[]},	
        {"answer":"coincidence", "title":	"стечение обстоятельств", synonyms:[]},	
        {"answer":"conquer", "title":	"завоевать", synonyms:[]},	
        {"answer":"cough", "title":	"кашель", synonyms:[]},	
        {"answer":"courage", "title":	"отвага", synonyms:[]},	
        {"answer":"courgettes", "title":	"кабачки", synonyms:[]},	
        {"answer":"cradle", "title":	"колыбель", synonyms:[]},	
        {"answer":"criticize", "title":	"критиковать", synonyms:[]},	
        {"answer":"cucumber", "title":	"огурец", synonyms:[]},	
        {"answer":"cure", "title":	"вылечивать", synonyms:[]},	
        {"answer":"delight", "title":	"восторг", synonyms:[]},	
        {"answer":"diary", "title":	"дневник", synonyms:[]},	
        {"answer":"discover", "title":	"открыть", synonyms:[]},	
        {"answer":"dish", "title":	"блюдо", synonyms:[]},	
        {"answer":"dust", "title":	"пыль", synonyms:[]},	
        {"answer":"earplugs", "title":	"беруши", synonyms:[]},	
        {"answer":"elbow", "title":	"локоть", synonyms:[]},	
        {"answer":"enormous", "title":	"огромный", synonyms:[]},	
        {"answer":"exciting", "title":	"восторг", synonyms:[]},	
        {"answer":"expect", "title":	"ожидать", synonyms:[]},	
        {"answer":"expectation", "title":	"надежда, ожидание", synonyms:[]},	
        {"answer":"fame", "title":	"известность", synonyms:[]},	
        {"answer":"farm", "title":	"разводить, выращивать", synonyms:[]},	
        {"answer":"fell sick", "title":	"чувствовать плохо", synonyms:[]},	
        {"answer":"fizzy", "title":	"газировка", synonyms:[]},	
        {"answer":"further", "title":	"в дальнейшем", synonyms:[]},	
        {"answer":"gam traffic", "title":	"час пик", synonyms:[]},	
        {"answer":"garlic", "title":	"чеснок", synonyms:[]},	
        {"answer":"get away", "title":	"избежать", synonyms:[]},	
        {"answer":"glorified", "title":	"прославлен", synonyms:[]},	
        {"answer":"grain", "title":	"зерно", synonyms:[]},	
        {"answer":"guided tour", "title":	"экскурсия", synonyms:[]},	
        {"answer":"haricot", "title":	"фасоль", synonyms:[]},	
        {"answer":"harness", "title":	"упряжь", synonyms:[]},	
        {"answer":"headband", "title":	"повязка на голове", synonyms:[]},	
        {"answer":"healthier", "title":	"здоровее", synonyms:[]},	
        {"answer":"heart", "title":	"сердце", synonyms:[]},	
        {"answer":"imagine", "title":	"представлять", synonyms:[]},	
        {"answer":"impostor", "title":	"самозванец, мошенник", synonyms:[]},	
        {"answer":"inexpensive", "title":	"недорогой", synonyms:[]},	
        {"answer":"inspiring", "title":	"вдохновляющий", synonyms:[]},	
        {"answer":"intense", "title":	"интенсивный", synonyms:[]},	
        {"answer":"jelly", "title":	"желе", synonyms:[]},	
        {"answer":"jewelry", "title":	"бижутерия", synonyms:[]},	
        {"answer":"jog", "title":	"медленный бег", synonyms:[]},	
        {"answer":"junk food", "title":	"вредная пища", synonyms:[]},	
        {"answer":"lamb", "title":	"ягненок", synonyms:[]},	
        {"answer":"lend", "title":	"давать в долг", synonyms:[]},	
        {"answer":"loans", "title":	"заем, ссуда", synonyms:[]},	
        {"answer":"look after", "title":	"присматривать за", synonyms:[]},	
        {"answer":"madness", "title":	"безумие", synonyms:[]},	
        {"answer":"miracle", "title":	"чудо", synonyms:[]},	
        {"answer":"mud", "title":	"грязь", synonyms:[]},	
        {"answer":"murder", "title":	"убийство", synonyms:[]},	
        {"answer":"mushroom", "title":	"гриб", synonyms:[]},	
        {"answer":"mussels", "title":	"моллюски, мидии", synonyms:[]},	
        {"answer":"notice", "title":	"замечание", synonyms:[]},	
        {"answer":"nurse", "title":	"медсестра", synonyms:[]},	
        {"answer":"oats", "title":	"овес", synonyms:[]},	
        {"answer":"octopus", "title":	"осьминог", synonyms:[]},	
        {"answer":"onion", "title":	"лук", synonyms:[]},	
        {"answer":"pack up", "title":	"собраться", synonyms:[]},	
        {"answer":"pan", "title":	"кастрюля", synonyms:[]},	
        {"answer":"parrot", "title":	"попугай", synonyms:[]},	
        {"answer":"passer by", "title":	"прохожий", synonyms:[]},	
        {"answer":"patient", "title":	"терпеливый", synonyms:[]},	
        {"answer":"pedometer", "title":	"шагомер", synonyms:[]},	
        {"answer":"pickles", "title":	"соленья", synonyms:[]},	
        {"answer":"plum", "title":	"слива", synonyms:[]},	
        {"answer":"possessions", "title":	"владения", synonyms:[]},	
        {"answer":"prediction", "title":	"предсказание", synonyms:[]},	
        {"answer":"promise", "title":	"обещать", synonyms:[]},	
        {"answer":"punish", "title":	"наказывать", synonyms:[]},	
        {"answer":"punishment", "title":	"наказание", synonyms:[]},	
        {"answer":"put up with", "title":	"смириться с", synonyms:[]},	
        {"answer":"quarter", "title":	"четверть", synonyms:[]},	
        {"answer":"raft", "title":	"скала", synonyms:[]},	
        {"answer":"rather humble", "title":	"довольно скромный", synonyms:[]},	
        {"answer":"reach", "title":	"достигать", synonyms:[]},	
        {"answer":"ridiculous", "title":	"смешной, нелепый", synonyms:[]},
        {"answer":"rise", "title":	"повышение", synonyms:[]},	
        {"answer":"rude", "title":	"грубый", synonyms:[]},	
        {"answer":"rush over", "title":	"час пик", synonyms:[]},	
        {"answer":"seasick", "title":	"морская болезнь", synonyms:[]},	
        {"answer":"settle", "title":	"обосновываться", synonyms:[]},	
        {"answer":"shark", "title":	"акула", synonyms:[]},	
        {"answer":"shower", "title":	"душ", synonyms:[]},	
        {"answer":"shrimps", "title":	"креветки", synonyms:[]},	
        {"answer":"sneeze", "title":	"чихать", synonyms:[]},	
        {"answer":"soldier", "title":	"солдат", synonyms:[]},	
        {"answer":"sore throat", "title":	"больное горло", synonyms:[]},	
        {"answer":"squeeze", "title":	"сдавливать", synonyms:[]},	
        {"answer":"squirt", "title":	"брызгать", synonyms:[]},	
        {"answer":"stairs", "title":	"лестница", synonyms:[]},	
        {"answer":"stuff", "title":	"материал", synonyms:[]},	
        {"answer":"suggest", "title":	"предлагать", synonyms:[]},	
        {"answer":"surgery", "title":	"хирургия", synonyms:[]},	
        {"answer":"surprisingly", "title":	"неожиданно", synonyms:[]},	
        {"answer":"survey", "title":	"опрос", synonyms:[]},	
        {"answer":"tip", "title":	"чаевые", synonyms:[]},	
        {"answer":"tough", "title":	"Трудный жесткий", synonyms:[]},	
        {"answer":"tourist attraction", "title":	"достопримечательности", synonyms:[]},	
        {"answer":"treasure", "title":	"сокровище", synonyms:[]},	
        {"answer":"trick", "title":	"шутка, уловка", synonyms:[]},	
        {"answer":"trigger", "title":	"вызывать срабатывание", synonyms:[]},	
        {"answer":"truth", "title":	"правда", synonyms:[]},	
        {"answer":"try out", "title":	"проверять", synonyms:[]},	
        {"answer":"tube", "title":	"метро", synonyms:[]},	
        {"answer":"twisting", "title":	"скручивание", synonyms:[]},	
        {"answer":"upstairs", "title":	"наверх", synonyms:[]},	
        {"answer":"value", "title":	"ценить", synonyms:[]},	
        {"answer":"waiters", "title":	"официант", synonyms:[]},	
        {"answer":"weakness", "title":	"слабость", synonyms:[]},	
        {"answer":"welfare office", "title":	"регистрационный офис", synonyms:[]},	
        {"answer":"wheat", "title":	"пшеница", synonyms:[]},	
        {"answer":"wheel", "title":	"колесо", synonyms:[]},	
        {"answer":"whilst", "title":	"в то время как", synonyms:[]},	
        {"answer":"worth", "title":	"ценность, имущество", synonyms:[]},	
        {"answer":"would rather", "title":	"лучше сделал бы", synonyms:[]},	
        {"answer":"wrist", "title":	"запястье", synonyms:[]},	
        {"answer":"yawn", "title":	"зевать", synonyms:[]},    
    ]
}

English.Lesson3 = {
    LessonType : 'eng',
    Name : 'Lesson 3',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"answer":"abandoned",	"title": "брошенный", synonyms:[]},	
        {"answer":"according",	"title": "согласно, следовательно", synonyms:[]},	
        {"answer":"adjective",	"title": "прилагательное", synonyms:[]},	
        {"answer":"annoy",	"title": "надоедать, раздражать", synonyms:[]},	
        {"answer":"appointment",	"title": "договор о встрече", synonyms:[]},	
        {"answer":"ashtray",	"title": "пепельница", synonyms:[]},	
        {"answer":"at last",	"title": "в конце концов", synonyms:[]},	
        {"answer":"attitude",	"title": "отношение", synonyms:[]},	
        {"answer":"bark",	"title": "лай", synonyms:[]},	
        {"answer":"bow",	"title": "лук", synonyms:[]},	
        {"answer":"break in",	"title": "взламывать", synonyms:[]},	
        {"answer":"breath",	"title": "дыхание", synonyms:[]},	
        {"answer":"bully",	"title": "хулиган", synonyms:[]},	
        {"answer":"carefree",	"title": "беззаботно", synonyms:[]},	
        {"answer":"carry out",	"title": "выполнять", synonyms:[]},	
        {"answer":"carry",	"title": "нести", synonyms:[]},	
        {"answer":"castle",	"title": "замок", synonyms:[]},	
        {"answer":"challenge",	"title": "испытание, вызов", synonyms:[]},	
        {"answer":"challenging",	"title": "испытывающий, сложный", synonyms:[]},	
        {"answer":"charity",	"title": "благотворительность", synonyms:[]},	
        {"answer":"cheered up",	"title": "воодушевленный", synonyms:[]},	
        {"answer":"cheetah",	"title": "гепард", synonyms:[]},	
        {"answer":"closer",	"title": "ближе", synonyms:[]},	
        {"answer":"commit",	"title": "совершить", synonyms:[]},	
        {"answer":"concil",	"title": "мэр", synonyms:[]},	
        {"answer":"convinient",	"title": "удобный", synonyms:[]},	
        {"answer":"crow",	"title": "толпа", synonyms:[]},	
        {"answer":"deep",	"title": "глубокий", synonyms:[]},	
        {"answer":"department store",	"title": "торговый центр", synonyms:[]},	
        {"answer":"deserve",	"title": "заслуживать", synonyms:[]},	
        {"answer":"differ",	"title": "отличаться", synonyms:[]},	
        {"answer":"difference",	"title": "разница", synonyms:[]},	
        {"answer":"different",	"title": "разный", synonyms:[]},	
        {"answer":"domestic",	"title": "домашний", synonyms:[]},	
        {"answer":"dominate",	"title": "доминанировать", synonyms:[]},	
        {"answer":"empowering",	"title": "уполномочивание", synonyms:[]},	
        {"answer":"entirely",	"title": "полностью", synonyms:[]},	
        {"answer":"entrepreneur",	"title": "предприниматель", synonyms:[]},	
        {"answer":"evidence",	"title": "доказательство", synonyms:[]},	
        {"answer":"extremely",	"title": "очень", synonyms:[]},	
        {"answer":"fair",	"title": "справедливый", synonyms:[]},	
        {"answer":"fairly",	"title": "довольно", synonyms:[]},	
        {"answer":"falter",	"title": "колебаться, спотыкаться", synonyms:[]},	
        {"answer":"fart",	"title": "пердеть", synonyms:[]},	
        {"answer":"faulty",	"title": "испорченный", synonyms:[]},	
        {"answer":"feed",	"title": "кормить", synonyms:[]},	
        {"answer":"fine",	"title": "штраф", synonyms:[]},	
        {"answer":"fit",	"title": "подходить по размеру", synonyms:[]},	
        {"answer":"follow",	"title": "следовать", synonyms:[]},	
        {"answer":"fraud",	"title": "мошенничество", synonyms:[]},	
        {"answer":"fur",	"title": "мех", synonyms:[]},	
        {"answer":"furious",	"title": "яростный", synonyms:[]},	
        {"answer":"get stuck",	"title": "застрять", synonyms:[]},	
        {"answer":"give a talk",	"title": "выступить с докладом", synonyms:[]},	
        {"answer":"give back",	"title": "возвращать", synonyms:[]},	
        {"answer":"give up",	"title": "бросать", synonyms:[]},	
        {"answer":"glacier",	"title": "ледник", synonyms:[]},	
        {"answer":"happiness",	"title": "радость", synonyms:[]},	
        {"answer":"heating",	"title": "отопление", synonyms:[]},	
        {"answer":"here you are",	"title": "вот, на", synonyms:[]},	
        {"answer":"hiking",	"title": "пеший туризм", synonyms:[]},	
        {"answer":"honest",	"title": "честный", synonyms:[]},	
        {"answer":"howl",	"title": "вой", synonyms:[]},	
        {"answer":"howling",	"title": "воющий", synonyms:[]},	
        {"answer":"humid",	"title": "влажный", synonyms:[]},	
        {"answer":"huts",	"title": "хижина", synonyms:[]},	
        {"answer":"incredible",	"title": "неимоверный", synonyms:[]},	
        {"answer":"inspire",	"title": "вдохновлять", synonyms:[]},	
        {"answer":"intended",	"title": "предназначен", synonyms:[]},	
        {"answer":"investigate",	"title": "расследовать", synonyms:[]},	
        {"answer":"issue",	"title": "вопрос, проблема", synonyms:[]},	
        {"answer":"joy",	"title": "радость", synonyms:[]},	
        {"answer":"liquid",	"title": "жидкий", synonyms:[]},	
        {"answer":"lizard",	"title": "ящерица", synonyms:[]},	
        {"answer":"look into",	"title": "разобраться в", synonyms:[]},	
        {"answer":"meaningful",	"title": "значительный", synonyms:[]},	
        {"answer":"monk",	"title": "монах", synonyms:[]},	
        {"answer":"mountain range",	"title": "горный хребет", synonyms:[]},	
        {"answer":"nanny",	"title": "няня", synonyms:[]},	
        {"answer":"nightmare",	"title": "ночной кошмар", synonyms:[]},	
        {"answer":"ostrish",	"title": "страус", synonyms:[]},	
        {"answer":"pavement",	"title": "мостовая", synonyms:[]},	
        {"answer":"peaceful",	"title": "мирный", synonyms:[]},	
        {"answer":"pigeon",	"title": "голубь", synonyms:[]},	
        {"answer":"plant",	"title": "растение", synonyms:[]},	
        {"answer":"pleasure",	"title": "удовольствие", synonyms:[]},	
        {"answer":"polluted",	"title": "загрязненный", synonyms:[]},	
        {"answer":"pot",	"title": "горшок", synonyms:[]},	
        {"answer":"pretty",	"title": "милый", synonyms:[]},	
        {"answer":"proudest",	"title": "горый", synonyms:[]},	
        {"answer":"pun",	"title": "каламбур", synonyms:[]},	
        {"answer":"really",	"title": "действительно", synonyms:[]},	
        {"answer":"refuse",	"title": "отказываться", synonyms:[]},	
        {"answer":"retire",	"title": "выйти на пенсию", synonyms:[]},	
        {"answer":"ridiculous",	"title": "странный нелепый", synonyms:[]},	
        {"answer":"rucksack",	"title": "рюкзак", synonyms:[]},	
        {"answer":"run out",	"title": "исчезнуть внезапно", synonyms:[]},	
        {"answer":"rural area",	"title": "сельская местность", synonyms:[]},	
        {"answer":"seals",	"title": "морские котики", synonyms:[]},	
        {"answer":"shark",	"title": "акула", synonyms:[]},	
        {"answer":"shoplifter",	"title": "магазинный вор", synonyms:[]},	
        {"answer":"sled",	"title": "санки", synonyms:[]},	
        {"answer":"sloth",	"title": "ленивец", synonyms:[]},	
        {"answer":"spare",	"title": "запасной, лишний", synonyms:[]},	
        {"answer":"spin",	"title": "вращаться", synonyms:[]},	
        {"answer":"splash out",	"title": "выплескивать", synonyms:[]},	
        {"answer":"stare",	"title": "глазеть", synonyms:[]},	
        {"answer":"stingy",	"title": "скупой", synonyms:[]},	
        {"answer":"stuff",	"title": "вещь, барахло", synonyms:[]},	
        {"answer":"suit",	"title": "подходить по внешнему виду", synonyms:[]},	
        {"answer":"suitable",	"title": "подоходящий", synonyms:[]},	
        {"answer":"survive",	"title": "уцелеть", synonyms:[]},	
        {"answer":"survived",	"title": "выживший", synonyms:[]},	
        {"answer":"take out rubbish",	"title": "выносить мусор", synonyms:[]},	
        {"answer":"take over",	"title": "наследовать, перенимать", synonyms:[]},	
        {"answer":"take up",	"title": "занимать место", synonyms:[]},	
        {"answer":"tend to",	"title": "склоняться к", synonyms:[]},	
        {"answer":"theft",	"title": "воровать", synonyms:[]},	
        {"answer":"thief",	"title": "вор", synonyms:[]},	
        {"answer":"think up",	"title": "придумать", synonyms:[]},	
        {"answer":"treat",	"title": "лечить", synonyms:[]},	
        {"answer":"trial",	"title": "судебное разбирательство", synonyms:[]},	
        {"answer":"tribe",	"title": "племя", synonyms:[]},	
        {"answer":"trip",	"title": "глюк", synonyms:[]},	
        {"answer":"try on",	"title": "примерять", synonyms:[]},	
        {"answer":"turn down",	"title": "отказываться", synonyms:[]},	
        {"answer":"turn into",	"title": "превратиться в", synonyms:[]},	
        {"answer":"tyre",	"title": "шина", synonyms:[]},	
        {"answer":"unfair",	"title": "недобросовестный", synonyms:[]},	
        {"answer":"victim",	"title": "жертва", synonyms:[]},	
        {"answer":"violent",	"title": "насильственный", synonyms:[]},	
        {"answer":"viral",	"title": "вирусный", synonyms:[]},	
        {"answer":"vomit",	"title": "тошнить", synonyms:[]},	
        {"answer":"weak",	"title": "слабый", synonyms:[]},	
        {"answer":"whereas",	"title": "в то время как", synonyms:[]},	
        {"answer":"wherever",	"title": "где бы ни", synonyms:[]},	
        {"answer":"whisper",	"title": "шептать", synonyms:[]},	
        {"answer":"worried",	"title": "взволнованный", synonyms:[]},	
    
    ]
}

English.Lesson4 = {
    LessonType : 'eng',
    Name : 'Lesson 4',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"answer":"bakery", "title": "пекарня", synonyms:[]},	
        {"answer":"have a barbecue", "title": "устроить барбекю", synonyms:[]},	
        {"answer":"have a party", "title": "устроить вечеринку", synonyms:[]},	
        {"answer":"propose", "title": "предложить", synonyms:[]},	 
        {"answer":"likely", "title": "скорее всего", synonyms:[]},	
        {"answer":"tell joke", "title": "рассказывать анекдот", synonyms:[]},	
        {"answer":"suddenly", "title": "вдруг", synonyms:[]},	
        {"answer":"doughnuts", "title": "пончики", synonyms:[]},	
        {"answer":"flexible hours", "title": "гибкий график", synonyms:[]},	
        {"answer":"skill", "title": "умение", synonyms:[]},	
        {"answer":"best wishes", "title": "с наилучшими пожеланиями", synonyms:[]},	
        {"answer":"best regard", "title": "с наилучшими пожеланиями", synonyms:[]},	
        {"answer":"take care", "title": "береги себя", synonyms:[]},	
        {"answer":"yours sincerely", "title": "искренне ваш", synonyms:[]},	
        {"answer":"sales rep", "title": "торговый представитель", synonyms:[]},	
        {"answer":"accounts", "title": "счета", "title": "банковское дело", synonyms:[]},	
        {"answer":"property", "title": "имущество", synonyms:[]},	
        {"answer":"delicious bagel", "title": "вкусный бублик", synonyms:[]},	
        {"answer":"countryside", "title": "сельская местность", synonyms:[]},	
        {"answer":"compound", "title": "соединенить", synonyms:[]},	
        {"answer":"on averange", "title": "в среднем", synonyms:[]},	
        {"answer":"inhabitant", "title": "житель", synonyms:[]},	
        {"answer":"annual", "title": "годовой", synonyms:[]},	
        {"answer":"appropriate", "title": "подходящий", synonyms:[]},	
        {"answer":"presenter", "title": "ведущий", synonyms:[]},	
        {"answer":"cashew", "title": "кешью", synonyms:[]},	
        {"answer":"strawberry", "title": "клубника", synonyms:[]},	
        {"answer":"invitation", "title": "приглашение", synonyms:[]},	
        {"answer":"make a speech", "title": "произнести речь", synonyms:[]},	
        {"answer":"make a phone call", "title": "позвонить", synonyms:[]},	
        {"answer":"make a decision", "title": "принять решение", synonyms:[]},	
        {"answer":"do a project", "title": "работать над проектом", synonyms:[]},	
        {"answer":"do business", "title": "заниматься бизнесом", synonyms:[]},	
        {"answer":"do well in", "title": "преуспевать в", synonyms:[]},	
        {"answer":"do badly in", "title": "быть плохим в", synonyms:[]},	
        {"answer":"pronounced", "title": "произнесённый", synonyms:[]},	
        {"answer":"pronunciation", "title": "произношение", synonyms:[]},	
        {"answer":"snails", "title": "улитка", synonyms:[]},	
        {"answer":"participle", "title": "причастие", synonyms:[]},	
        {"answer":"approach", "title": "подход", synonyms:[]},	
        {"answer":"flip", "title": "щелкнуть", synonyms:[]},	
        {"answer":"achieve", "title": "достигать", synonyms:[]},	
        {"answer":"launch", "title": "запуск", synonyms:[]},	
        {"answer":"disease", "title": "болезнь", synonyms:[]},	
        {"answer":"fewer", "title": "меньше", synonyms:[]},	
        {"answer":"affirmative", "title": "утвердительный", synonyms:[]},	
        {"answer":"sailor", "title": "матрос", synonyms:[]},	
        {"answer":"suitcase", "title": "чемодан", synonyms:[]},	
        {"answer":"money belt", "title": "пояс для денег", synonyms:[]},	
        {"answer":"sequence", "title": "последовательность", synonyms:[]},	
        {"answer":"natural wonder", "title": "чудо природы", synonyms:[]},	
        {"answer":"equally", "title": "одинаково", synonyms:[]},	
        {"answer":"beyond", "title": "по ту сторону", synonyms:[]},	
        {"answer":"vowels", "title": "гласные", synonyms:[]},	
        {"answer":"bracket", "title": "скобка", synonyms:[]},	
        {"answer":"knive", "title": "резать ножом", synonyms:[]},	
        {"answer":"knife", "title": "нож", synonyms:[]},	
        {"answer":"certain", "title": "определенный", synonyms:[]},	
        {"answer":"flu", "title": "грипп", synonyms:[]},	
        {"answer":"gain", "title": "усиление", synonyms:[]},	
        {"answer":"regime", "title": "режим", synonyms:[]},	
        {"answer":"extend", "title": "расширять", "title": "продлевать", synonyms:[]},	
        {"answer":"stationary shop", "title": "канцелярский магазин", synonyms:[]},	
        {"answer":"questionnaire", "title": "опросный лист", synonyms:[]},	
        {"answer":"ancient", "title": "древний", synonyms:[]},	
        {"answer":"fire fighter", "title": "пожарный", synonyms:[]},	
        {"answer":"funding", "title": "финансирование", synonyms:[]},	
        {"answer":"neccesary", "title": "необходимо", synonyms:[]},	
        {"answer":"emphasis", "title": "особое внимание", "title": "акцент", synonyms:[]},	
        {"answer":"secure", "title": "безопасный", synonyms:[]},	
        {"answer":"particular", "title": "конкретный", synonyms:[]},	
        {"answer":"practise", "title": "практика", synonyms:[]},	
        {"answer":"scarf", "title": "шарф", synonyms:[]},	
        {"answer":"neighbourhood", "title": "соседство", "title": "окрестности", synonyms:[]},	
        {"answer":"funky", "title": "трусливый", synonyms:[]},	
        {"answer":"homespun", "title": "домотканный", synonyms:[]},	
        {"answer":"wage", "title": "зарплата", synonyms:[]},	
        {"answer":"poverty", "title": "бедность", synonyms:[]},	
        {"answer":"hug", "title": "объятие", synonyms:[]},	
        {"answer":"clearing", "title": "поляна", synonyms:[]},	
        {"answer":"lower", "title": "ниже", synonyms:[]},	
        {"answer":"plural", "title": "множественное число", synonyms:[]},	
        {"answer":"on one occasion", "title": "в одном случае", synonyms:[]},	
        {"answer":"buddy", "title": "дружище", synonyms:[]},	
        {"answer":"earthquake", "title": "землетрясение", synonyms:[]},	
        {"answer":"gerbils", "title": "песчаная крыса", synonyms:[]},	
        {"answer":"guard", "title": "охрана", synonyms:[]},	
        {"answer":"astonishing", "title": "удивительный", synonyms:[]},	
        {"answer":"uncertain", "title": "изменчевый", synonyms:[]},	
        {"answer":"elusive", "title": "неуловимый", synonyms:[]},	
        {"answer":"terrifying", "title": "ужасающий", synonyms:[]},	
        {"answer":"graduated", "title": "закончил", synonyms:[]},	
        {"answer":"be interested in", "title": "быть заинтересованным в", synonyms:[]},	
        {"answer":"however", "title": "тем не менее", synonyms:[]},	
        {"answer":"stem", "title": "стебель", synonyms:[]},	
        {"answer":"complain", "title": "жалоба", synonyms:[]},	
        {"answer":"concern", "title": "беспокойство", synonyms:[]},	
        {"answer":"noodles", "title": "лапша", synonyms:[]},	
        {"answer":"benifit", "title": "выгода", synonyms:[]},	
        {"answer":"cheer", "title": "ура", synonyms:[]},	
        {"answer":"embrassed", "title": "смущенный", "title": "растерянный", synonyms:[]},	
        {"answer":"consequence", "title": "следствие", "title": "последствие", synonyms:[]},	
        {"answer":"election", "title": "выборы", synonyms:[]},	
        {"answer":"waste", "title": "отходы", synonyms:[]},	
        {"answer":"silly", "title": "глупый", synonyms:[]},	
        {"answer":"distracted", "title": "рассеянный", synonyms:[]},	
        {"answer":"addictive", "title": "привыкание", synonyms:[]},	
        {"answer":"degree", "title": "степень", synonyms:[]},	
        {"answer":"tablet", "title": "планшет", synonyms:[]},	
        {"answer":"interact", "title": "взаимодействовать", synonyms:[]},	
        {"answer":"ladder", "title": "лестница", synonyms:[]},	
        {"answer":"give away", "title": "раздавать", synonyms:[]},	
        {"answer":"superstition", "title": "суеверие", synonyms:[]},	
        {"answer":"exclaim", "title": "восклицать", synonyms:[]},	
        {"answer":"biopic", "title": "фильм о биографии", synonyms:[]},	
        {"answer":"cartoon", "title": "мультфильм", synonyms:[]},	
        {"answer":"avenger", "title": "мститель", synonyms:[]},	
        {"answer":"myths", "title": "мистика", "title": "мифы", synonyms:[]},	
        {"answer":"paradise", "title": "рай", synonyms:[]},	
        {"answer":"defeat", "title": "поражение", synonyms:[]},	
        {"answer":"reported speech", "title": "косвенная речь", synonyms:[]},	
        {"answer":"world-shaking", "title": "потрясший весь мир", synonyms:[]},	
        {"answer":"related", "title": "связанный", synonyms:[]},	
        {"answer":"stroke", "title": "поглаживать", synonyms:[]},	
        {"answer":"chase", "title": "преследовать", synonyms:[]},	
        {"answer":"extra terrestrial", "title": "внеземная жизнь", synonyms:[]},	
        {"answer":"damn", "title": "черт", synonyms:[]},	
        {"answer":"prompt", "title": "подсказка", synonyms:[]},	
        {"answer":"wash", "title": "стирка", synonyms:[]},	
        {"answer":"episode", "title": "серия", "title": "эпизод", synonyms:[]},	
        {"answer":"mock", "title": "троллить", "title": "издеваться", synonyms:[]},	
        {"answer":"helpful", "title": "полезный", synonyms:[]},	
        {"answer":"bog", "title": "болото", synonyms:[]},	
        {"answer":"fashionable", "title": "модный", synonyms:[]},	
        {"answer":"hugely", "title": "очень", synonyms:[]},	
        {"answer":"daily", "title": "ежедневно", synonyms:[]},	
        {"answer":"collocation", "title": "словосочетание", synonyms:[]},	
        {"answer":"grumpy", "title": "сердитый", synonyms:[]},	
        {"answer":"overnight", "title": "быстро", "title": "за ночь", synonyms:[]},	
        {"answer":"campaign", "title": "кампания", synonyms:[]},	
        {"answer":"childcare", "title": "уход за детими", synonyms:[]},	
        {"answer":"concierge", "title": "консьерж", synonyms:[]},	
        {"answer":"former", "title": "бывший", synonyms:[]},	
        {"answer":"midnight", "title": "полночь", synonyms:[]},	
        {"answer":"hang on", "title": "повесите на трубке", synonyms:[]},	
        {"answer":"hold on", "title": "оставайтесь на линии", synonyms:[]},	
        {"answer":"go-karts", "title": "картинг", synonyms:[]},	
    
    ]
}

English.Lesson5 = {
    LessonType : 'eng',
    Name : 'Lesson 5',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson6 = {
    LessonType : 'eng',
    Name : 'Lesson 6',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson7 = {
    LessonType : 'eng',
    Name : 'Lesson 7',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson8 = {
    LessonType : 'eng',
    Name : 'Lesson 8',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson9 = {
    LessonType : 'eng',
    Name : 'Lesson 9',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson10 = {
    LessonType : 'eng',
    Name : 'Lesson 10',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson11 = {
    LessonType : 'eng',
    Name : 'Lesson 11',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson12 = {
    LessonType : 'eng',
    Name : 'Lesson 12',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}

English.Lesson13 = {
    LessonType : 'eng',
    Name : 'Lesson 13',
    Directory : 'English.Pre-intermediate',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
    
    ]
}
