var Serbian = {};
Serbian.Lesson1 = {
    LessonType : 'srb',
    Name : 'Цвета и прилагательные',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"цвет","answer":"боја", synonyms:[] },
        {"title":"оттенок","answer":"нијанса", synonyms:[] },
        {"title":"тон","answer":"тон", synonyms:[] },
        {"title":"радуга","answer":"дуга", synonyms:[] },
        {"title":"белый","answer":"бео", synonyms:[] },
        {"title":"чёрный","answer":"црн", synonyms:[] },
        {"title":"серый","answer":"сив", synonyms:[] },
        {"title":"зелёный","answer":"зелен", synonyms:[] },
        {"title":"жёлтый","answer":"жут", synonyms:[] },
        {"title":"красный","answer":"црвен", synonyms:[] },
        {"title":"голубой","answer":"плав", synonyms:[] },
        {"title":"розовый","answer":"ружичаст", synonyms:[] },
        {"title":"оранжевый","answer":"наранџаст", synonyms:[] },
        {"title":"фиолетовый","answer":"љубичаст", synonyms:[] },
        {"title":"лиловый,коричневый","answer":"смеђ", synonyms:[] },
        {"title":"золотой","answer":"златан", synonyms:[] },
        {"title":"серебристый","answer":"сребрни", synonyms:[] },
        {"title":"бежевый","answer":"беж", synonyms:[] },
        {"title":"кремовый","answer":"крем боје", synonyms:[] },
        {"title":"бирюзовый","answer":"тиркизни", synonyms:[] },
        {"title":"вишнёвый","answer":"боја вишње", synonyms:[] },
        {"title":"малиновый","answer":"боја малине", synonyms:[] },
        {"title":"светлый","answer":"светао", synonyms:[] },
        {"title":"тёмный","answer":"таман", synonyms:[] },
        {"title":"яркий","answer":"сјајан", synonyms:[] },
        {"title":"цветной(карандаш)","answer":"обојeн", synonyms:[] },
        {"title":"цветной(фильм)","answer":"у боји", synonyms:[] },
        {"title":"чёрно-белый","answer":"црно-бели", synonyms:[] },
        {"title":"одноцветный","answer":"једнобојан", synonyms:[] },
        {"title":"разноцветный","answer":"разнобојан", synonyms:[] },
        {"title":"богатый","answer":"богат", synonyms:[] },
        {"title":"бедный","answer":"сиромах", synonyms:[] },
        {"title":"больной","answer":"болестан", synonyms:[] },
        {"title":"здоровый","answer":"здрав", synonyms:[] },
        {"title":"большой","answer":"велик", synonyms:[] },
        {"title":"маленький","answer":"мали", synonyms:[] },
        {"title":"быстро","answer":"брзо", synonyms:[] },
        {"title":"медленно","answer":"полако", synonyms:[] },
        {"title":"быстрый","answer":"брз", synonyms:[] },
        {"title":"медленный","answer":"спор", synonyms:[] },
        {"title":"весёлый","answer":"весео", synonyms:[] },
        {"title":"грустный","answer":"тужан", synonyms:[] },
        {"title":"вместе","answer":"заједно", synonyms:[] },
        {"title":"отдельно","answer":"посебно", synonyms:[] },
        {"title":"вслух","answer":"гласно", synonyms:[] },
        {"title":"про себя","answer":"у себи", synonyms:[] },
        {"title":"высокий","answer":"висок", synonyms:[] },
        {"title":"низкий","answer":"низак", synonyms:[] },
        {"title":"глубокий","answer":"дубок", synonyms:[] },
        {"title":"мелкий","answer":"плитак", synonyms:[] },
        {"title":"далёкий","answer":"далек", synonyms:[] },
        {"title":"близкий","answer":"близак", synonyms:[] },
        {"title":"далеко","answer":"далеко", synonyms:[] },
        {"title":"рядом","answer":"близу", synonyms:[] },
        {"title":"длинный","answer":"дугачак", synonyms:[] },
        {"title":"короткий","answer":"кратак", synonyms:[] },
        {"title":"добрый","answer":"добар", synonyms:[] },
        {"title":"злой","answer":"зао", synonyms:[] },
        {"title":"женатый","answer":"ожењен", synonyms:[] },
        {"title":"холостой","answer":"неожењен", synonyms:[] },
        {"title":"запретить","answer":"забранити", synonyms:[] },
        {"title":"разрешить","answer":"дозволити", synonyms:[] },
        {"title":"конец","answer":"крај", synonyms:[] },
        {"title":"начало","answer":"почетак", synonyms:[] },
        {"title":"последний","answer":"последњи", synonyms:[] },
        {"title":"преступление","answer":"злочин", synonyms:[] },
        {"title":"наказание","answer":"казна", synonyms:[] },
        {"title":"приказать","answer":"наредити", synonyms:[] },
        {"title":"подчиниться","answer":"потчинити се", synonyms:[] },
        {"title":"прямой","answer":"прав", synonyms:[] },
        {"title":"кривой","answer":"искривљен", synonyms:[] },
        {"title":"сильный","answer":"снажан", synonyms:[] },
        {"title":"слабый","answer":"слаб", synonyms:[] },
        {"title":"старый","answer":"стар", synonyms:[] },
        {"title":"молодой","answer":"млад", synonyms:[] },
        {"title":"новый","answer":"нов", synonyms:[] },
        {"title":"твёрдый","answer":"чврст", synonyms:[] },
        {"title":"мягкий","answer":"мек", synonyms:[] },
        {"title":"тёплый","answer":"топао", synonyms:[] },
        {"title":"холодный","answer":"хладан", synonyms:[] },
        {"title":"толстый","answer":"дебео", synonyms:[] },
        {"title":"худой","answer":"мршав", synonyms:[] },
        {"title":"узкий","answer":"узак", synonyms:[] },
        {"title":"широкий","answer":"широк", synonyms:[] },
        {"title":"хороший","answer":"добар", synonyms:[] },
        {"title":"плохой","answer":"рђав", synonyms:[] },
        {"title":"храбрый","answer":"храбар", synonyms:[] },
        {"title":"трусливый","answer":"плашљив", synonyms:[] },
    ]
}

Serbian.Lesson2 = {
    LessonType : 'srb',
    Name : 'Вопросы и приветствие',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"здороваться","answer":"поздрављати се", synonyms:[] },
        {"title":"приветствовать","answer":"поздрављати", synonyms:[] },
        {"title":"как дела?","answer":"како си?", synonyms:[] },
        {"title":"что нового?","answer":"шта има ново?", synonyms:[] },
        {"title":"до свидания,прощайте","answer":"до виђења", synonyms:[] },
        {"title":"доскорой встречи","answer":"до скорог виђења", synonyms:[] },
        {"title":"прощай","answer":"збогом", synonyms:[] },
        {"title":"прощаться","answer":"опраштати се", synonyms:[] },
        {"title":"большое спасибо","answer":"хвала лепо", synonyms:[] },
        {"title":"пожалуйста ответ","answer":"изволите", synonyms:[] },
        {"title":"не стоит благодарности,не за что","answer":"нема на чему", synonyms:[] },
        {"title":"извини","answer":"извини", synonyms:[] },
        {"title":"извинять","answer":"извињавати", synonyms:[] },
        {"title":"извиняться","answer":"извињавати се", synonyms:[] },
        {"title":"простите","answer":"опростите", synonyms:[] },
        {"title":"прощать","answer":"опраштати", synonyms:[] },
        {"title":"конечно","answer":"свакако", synonyms:[] },
        {"title":"конечно нет","answer":"разуме се не", synonyms:[] },
        {"title":"согласен","answer":"слажем се", synonyms:[] },
        {"title":"хватит","answer":"доста", synonyms:[] },
        {"title":"кто?","answer":"ко?", synonyms:[] },
        {"title":"что?","answer":"шта?", synonyms:[] },
        {"title":"где?","answer":"где?", synonyms:[] },
        {"title":"куда?","answer":"куда?", synonyms:[] },
        {"title":"откуда?","answer":"откуд?", synonyms:[] },
        {"title":"когда?","answer":"када?", synonyms:[] },
        {"title":"зачем?","answer":"зашто?", synonyms:[] },
        {"title":"для чего?","answer":"због чега?", synonyms:[] },
        {"title":"как?","answer":"како?", synonyms:[] },
        {"title":"какой?","answer":"какав?", synonyms:[] },
        {"title":"который?","answer":"који?", synonyms:[] },
        {"title":"кому?","answer":"коме?", synonyms:[] },
        {"title":"о ком?","answer":"о коме?", synonyms:[] },
        {"title":"о чём?","answer":"о чиме?", synonyms:[] },
        {"title":"с кем?","answer":"с ким?", synonyms:[] },
        {"title":"чей?","answer":"чији?", synonyms:[] },
        {"title":"с (кем-либо)","answer":"с", synonyms:[] },
        {"title":"без","answer":"без", synonyms:[] },
        {"title":"в (предлог движения)","answer":"у", synonyms:[] },
        {"title":"о (говорить о)","answer":"о", synonyms:[] },
        {"title":"перед (временя)","answer":"пре", synonyms:[] },
        {"title":"перед (пространство)","answer":"испред", synonyms:[] },
        {"title":"под, внизу","answer":"испод", synonyms:[] },
        {"title":"над, наверху","answer":"изнад", synonyms:[] },
        {"title":"на (чём-то)","answer":"на", synonyms:[] },
        {"title":"из (откуда)","answer":"из", synonyms:[] },
        {"title":"из (чего)","answer":"од", synonyms:[] },
        {"title":"через (временя)","answer":"кроз", synonyms:[] },
        {"title":"через (препятствие)","answer":"преко", synonyms:[] },
        {"title":"здесь","answer":"овде", synonyms:[] },
        {"title":"там","answer":"тамо", synonyms:[] },
        {"title":"где-то","answer":"негде", synonyms:[] },
        {"title":"нигде","answer":"нигде", synonyms:[] },
        {"title":"у, около","answer":"код", synonyms:[] },
        {"title":"сюда","answer":"овамо", synonyms:[] },
        {"title":"туда","answer":"тамо", synonyms:[] },
        {"title":"отсюда","answer":"одавде", synonyms:[] },
        {"title":"оттуда","answer":"оданде", synonyms:[] },
        {"title":"далеко","answer":"далеко", synonyms:[] },
        {"title":"около (приблизительно / рядом)","answer":"око", synonyms:[] },
        {"title":"близко, рядом(недалеко)","answer":"близу", synonyms:[] },
        {"title":"недалеко","answer":"недалеко", synonyms:[] },
        {"title":"левый","answer":"лев", synonyms:[] },
        {"title":"налево,слева","answer":"лево", synonyms:[] },
        {"title":"правый","answer":"десан", synonyms:[] },
        {"title":"направо,справа","answer":"десно", synonyms:[] },
        {"title":"спереди","answer":"спреда", synonyms:[] },
        {"title":"передний","answer":"предњи", synonyms:[] },
        {"title":"вперёд","answer":"унапред", synonyms:[] },
        {"title":"сзади","answer":"одостраг", synonyms:[] },
        {"title":"назад","answer":"унатраг", synonyms:[] },
        {"title":"середина","answer":"средина", synonyms:[] },
        {"title":"посередине","answer":"у средини", synonyms:[] },
        {"title":"сбоку, со стороны","answer":"са стране", synonyms:[] },
        {"title":"везде","answer":"свугде", synonyms:[] },
        {"title":"вокруг","answer":"около", synonyms:[] },
        {"title":"изнутри","answer":"изнутра", synonyms:[] },
        {"title":"куда-то","answer":"некуд", synonyms:[] },
        {"title":"напрямик","answer":"право", synonyms:[] },
        {"title":"обратно","answer":"повратно", synonyms:[] },
        {"title":"откуда-нибудь","answer":"однекуд", synonyms:[] },
        {"title":"откуда-то","answer":"однекле", synonyms:[] },
    ]
}

Serbian.Lesson3_1 = {
    LessonType : 'srb',
    Name : 'Глаголы часть 1',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"бежать","answer":"трчати", synonyms:[] },
        {"title":"бояться","answer":"плашити се", synonyms:["бојати се"] },
        {"title":"брать","answer":"брати", synonyms:[] },
        {"title":"быть","answer":"бити", synonyms:[] },
        {"title":"видеть","answer":"видети", synonyms:[] },
        {"title":"владеть","answer":"владати", synonyms:[] },
        {"title":"возражать","answer":"замерати", synonyms:[] },
        {"title":"входить(в комнату и т.п.)","answer":"ући", synonyms:[] },
        {"title":"выбирать","answer":"бирати", synonyms:[] },
        {"title":"выходить(из дома)","answer":"излазити", synonyms:[] },
        {"title":"говорить(разговаривать)","answer":"разговарати", synonyms:[] },
        {"title":"готовить(обед)","answer":"кувати", synonyms:[] },
        {"title":"давать","answer":"давати", synonyms:[] },
        {"title":"делать","answer":"радити", synonyms:[] },
        {"title":"доверять","answer":"поверавати", synonyms:[] },
        {"title":"думать","answer":"мислити", synonyms:[] },
        {"title":"жаловаться","answer":"жалити се", synonyms:[] },
        {"title":"ждать","answer":"чекати", synonyms:[] },
        {"title":"требовать","answer":"захтевати", synonyms:[] },
        {"title":"забывать","answer":"заборавити", synonyms:[] },
        {"title":"завтракать","answer":"доручковати", synonyms:[] },
        {"title":"заказывать","answer":"наручивати", synonyms:[] },
        {"title":"заканчивать","answer":"завршавати", synonyms:[] },
        {"title":"замечать(увидеть)","answer":"запажати", synonyms:[] },
        {"title":"записывать","answer":"записивати", synonyms:[] },
        {"title":"защищать(страну)","answer":"бранити", synonyms:[] },
        {"title":"звать(на помощь и т.п.)","answer":"звати", synonyms:[] },
        {"title":"знать(кого-л.)","answer":"познавати", synonyms:[] },
        {"title":"знать(что-л.)","answer":"знати", synonyms:[] },
        {"title":"играть","answer":"играти", synonyms:[] },
        {"title":"идти","answer":"ићи", synonyms:[] },
        {"title":"изменить(поменять)","answer":"променити", synonyms:[] },
        {"title":"изучать","answer":"проучавати", synonyms:[] },
        {"title":"иметь","answer":"имати", synonyms:[] },
        {"title":"интересоваться","answer":"интересовати се", synonyms:[] },
        {"title":"информировать","answer":"информирати", synonyms:[] },
        {"title":"искать","answer":"тражити", synonyms:[] },
        {"title":"контролировать","answer":"контролисати", synonyms:[] },
        {"title":"красть","answer":"красти", synonyms:[] },
        {"title":"кричать","answer":"викати", synonyms:[] },
        {"title":"купаться(в море и т.п.)","answer":"купати се", synonyms:[] },
        {"title":"лететь","answer":"летети", synonyms:[] },
        {"title":"ловить","answer":"ловити", synonyms:[] },
        {"title":"ломать","answer":"ломити", synonyms:[] },
        {"title":"любить(кого-л.)","answer":"волети", synonyms:[] },
        {"title":"молиться","answer":"молити се", synonyms:[] },
        {"title":"молчать","answer":"ћутати", synonyms:[] },
        {"title":"мочь","answer":"моћи", synonyms:[] },
        {"title":"наблюдать","answer":"гледати", synonyms:[] },
        {"title":"надеяться","answer":"надати се", synonyms:[] },
        {"title":"наказывать","answer":"кажњавати", synonyms:[] },
        {"title":"настаивать(упорствовать)","answer":"инсистрирати", synonyms:[] },
        {"title":"находить","answer":"налазити", synonyms:[] },
        {"title":"начинать","answer":"починати", synonyms:[] },
        {"title":"недооценивать","answer":"потцењивати", synonyms:[] },
        {"title":"нравиться","answer":"свиђати се", synonyms:[] },
        {"title":"обедать","answer":"ручати", synonyms:[] },
        {"title":"обещать","answer":"обећавати", synonyms:[] },
        {"title":"обманывать","answer":"варати", synonyms:[] },
        {"title":"обсуждать","answer":"дискутовати", synonyms:[] },
        {"title":"объединять","answer":"обједињавати", synonyms:[] },
        {"title":"объяснять","answer":"објашњавати", synonyms:[] },
        {"title":"означать","answer":"означавати", synonyms:[] },
        {"title":"освобождать(город)","answer":"ослобођавати", synonyms:[] },
        {"title":"оскорблять","answer":"вређати", synonyms:[] },
        {"title":"останавливаться","answer":"заустављати се", synonyms:[] },
        {"title":"отвечать","answer":"одговарати", synonyms:[] },
        {"title":"отказываться","answer":"отказивати се", synonyms:[] },
        {"title":"открывать(дверь и т.п.)","answer":"отварати", synonyms:[] },
        {"title":"отправлять","answer":"слати", synonyms:[] },
        {"title":"охотиться","answer":"ловити", synonyms:[] },
        {"title":"ошибаться","answer":"грешити", synonyms:[] },
        {"title":"падать","answer":"падати", synonyms:[] },
        {"title":"переводить(текст)","answer":"преводити", synonyms:[] },
        {"title":"писать","answer":"писати", synonyms:[] },

    ]
}

Serbian.Lesson3_2 = {
    LessonType : 'srb',
    Name : 'Глаголы часть 2',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"плавать","answer":"пливати", synonyms:[] },
        {"title":"плакать","answer":"плакати", synonyms:[] },
        {"title":"планировать","answer":"планирати", synonyms:[] },
        {"title":"платить","answer":"платити", synonyms:[] },
        {"title":"поворачивать","answer":"скретати", synonyms:[] },
        {"title":"повторять","answer":"понављати", synonyms:[] },
        {"title":"подписывать","answer":"подписивати", synonyms:[] },
        {"title":"подсказать(отгадку)","answer":"алудирати", synonyms:[] },
        {"title":"показывать","answer":"показивати", synonyms:[] },
        {"title":"помогать","answer":"помагати", synonyms:[] },
        {"title":"понимать","answer":"разумевати", synonyms:[] },
        {"title":"предвидеть(ожидать)","answer":"предвидети", synonyms:[] },
        {"title":"предлагать","answer":"нудити", synonyms:[] },
        {"title":"предпочитать","answer":"давати предност", synonyms:[] },
        {"title":"предупреждать","answer":"опомињати", synonyms:[] },
        {"title":"прекращать","answer":"прекидати", synonyms:[] },
        {"title":"приглашать","answer":"позивати", synonyms:[] },
        {"title":"приезжать","answer":"долазити", synonyms:[] },
        {"title":"приказывать","answer":"наређивати", synonyms:[] },
        {"title":"принадлежать","answer":"припадати", synonyms:[] },
        {"title":"пробовать(пытаться)","answer":"пробати", synonyms:[] },
        {"title":"продавать","answer":"продавати", synonyms:[] },
        {"title":"продолжать","answer":"продужавати", synonyms:[] },
        {"title":"произносить(слово)","answer":"изговарати", synonyms:[] },
        {"title":"пропускать(занятия и т.п.)","answer":"пропуштати", synonyms:[] },
        {"title":"просить","answer":"молити", synonyms:[] },
        {"title":"прощать","answer":"опраштати", synonyms:[] },
        {"title":"прятать","answer":"крити", synonyms:[] },
        {"title":"путать(ошибаться)","answer":"бркати", synonyms:[] },
        {"title":"работать","answer":"радити", synonyms:[] },
        {"title":"разрешать","answer":"решавати", synonyms:[] },
        {"title":"рассчитывать на","answer":"рачунати на", synonyms:[] },
        {"title":"резервировать","answer":"резервисати", synonyms:[] },
        {"title":"рекомендовать","answer":"рекомендовати", synonyms:[] },
        {"title":"ронять","answer":"испуштати", synonyms:[] },
        {"title":"ругать","answer":"грдити", synonyms:[] },
        {"title":"руководить(чем-л.)","answer":"руководити", synonyms:[] },
        {"title":"рыть","answer":"копати", synonyms:[] },
        {"title":"садиться","answer":"седати", synonyms:[] },
        {"title":"сказать","answer":"рећи", synonyms:[] },
        {"title":"следовать за","answer":"пратити", synonyms:[] },
        {"title":"слышать","answer":"чути", synonyms:[] },
        {"title":"смеяться","answer":"смејати се", synonyms:[] },
        {"title":"снимать(напр.квартиру)","answer":"изнајмљивати", synonyms:[] },
        {"title":"советовать","answer":"саветовати", synonyms:[] },
        {"title":"соглашаться","answer":"слагати се", synonyms:[] },
        {"title":"сожалеть","answer":"жалити", synonyms:[] },
        {"title":"создать","answer":"створити", synonyms:[] },
        {"title":"сомневаться","answer":"сумњати се", synonyms:[] },
        {"title":"сохранять","answer":"чувати", synonyms:[] },
        {"title":"спасать","answer":"спасавати", synonyms:[] },
        {"title":"спрашивать","answer":"питати", synonyms:[] },
        {"title":"спускаться","answer":"спуштати се", synonyms:[] },
        {"title":"сравнивать","answer":"упоређивати", synonyms:[] },
        {"title":"стоить","answer":"коштати", synonyms:[] },
        {"title":"стрелять","answer":"пуцати", synonyms:[] },
        {"title":"существовать","answer":"постојати", synonyms:[] },
        {"title":"считать(подсчитывать)","answer":"рачунати", synonyms:[] },
        {"title":"торопиться","answer":"журити се", synonyms:[] },
        {"title":"требоваться","answer":"требати", synonyms:[] },
        {"title":"трогать","answer":"дирати", synonyms:[] },
        {"title":"убивать","answer":"убијати", synonyms:[] },
        {"title":"угрожать","answer":"претити", synonyms:[] },
        {"title":"удивляться","answer":"изненађивати се", synonyms:[] },
        {"title":"ужинать","answer":"вечерати", synonyms:[] },
        {"title":"украшать","answer":"китити", synonyms:[] },
        {"title":"улыбаться","answer":"осмехивати се", synonyms:[] },
        {"title":"упоминать","answer":"спомињати", synonyms:[] },
        {"title":"участвовать","answer":"учествовати", synonyms:[] },
        {"title":"хвастаться","answer":"хвалисати се", synonyms:[] },
        {"title":"хотеть","answer":"хтети", synonyms:[] },
        {"title":"хотеть есть","answer":"бити гладан", synonyms:[] },
        {"title":"хотеть пить","answer":"бити жедан", synonyms:[] },
        {"title":"читать","answer":"читати", synonyms:[] },
        {"title":"шутить","answer":"шалити се", synonyms:[] },
        {"title":"родиться","answer":"родити се", synonyms:[] },
        {"title":"умереть","answer":"умрети", synonyms:[] },
    ]
}

Serbian.Lesson4 = {
    LessonType : 'srb',
    Name : 'Наречия',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"во-первых","answer":"прво", synonyms:[] },
        {"title":"во-вторых","answer":"друго", synonyms:[] },
        {"title":"в-третьих","answer":"треће", synonyms:[] },
        {"title":"вдруг","answer":"одједном", synonyms:[] },
        {"title":"вначале","answer":"у почетку", synonyms:[] },
        {"title":"впервые","answer":"први пут", synonyms:[] },
        {"title":"задолго до","answer":"много пре", synonyms:[] },
        {"title":"заново","answer":"поново", synonyms:[] },
        {"title":"насовсем","answer":"заувек", synonyms:[] },
        {"title":"никогда","answer":"никад", synonyms:[] },
        {"title":"опять","answer":"опет", synonyms:[] },
        {"title":"теперь","answer":"сада", synonyms:[] },
        {"title":"часто","answer":"често", synonyms:[] },
        {"title":"тогда","answer":"тада", synonyms:[] },
        {"title":"срочно","answer":"хитно", synonyms:[] },
        {"title":"обычно","answer":"обично", synonyms:[] },
        {"title":"кстати","answer":"узгред речено", synonyms:[] },
        {"title":"возможно","answer":"можда", synonyms:[] },
        {"title":"вероятно","answer":"вероватно", synonyms:[] },
        {"title":"может быть","answer":"може бити", synonyms:[] },
        {"title":"кроме того,","answer":"осим тога", synonyms:[] },
        {"title":"поэтому","answer":"зато", synonyms:[] },
        {"title":"несмотря на","answer":"без обзира на", synonyms:[] },
        {"title":"благодаря","answer":"захваљујући", synonyms:[] },
        {"title":"что(местоимение)","answer":"шта", synonyms:[] },
        {"title":"что(союз)","answer":"да", synonyms:[] },
        {"title":"что-нибудь,что-то","answer":"нешто", synonyms:[] },
        {"title":"ничего","answer":"ништа", synonyms:[] },
        {"title":"кто","answer":"ко", synonyms:[] },
        {"title":"кто-нибудь,кто-то","answer":"неко", synonyms:[] },
        {"title":"никто","answer":"нико", synonyms:[] },
        {"title":"никуда","answer":"никуд", synonyms:[] },
        {"title":"ничей","answer":"ничији", synonyms:[] },
        {"title":"чей-нибудь","answer":"нечији", synonyms:[] },
        {"title":"так","answer":"тако", synonyms:[] },
        {"title":"также","answer":"такође", synonyms:[] },
        {"title":"тоже","answer":"исто", synonyms:[] },
        {"title":"почему?","answer":"зашто?", synonyms:[] },
        {"title":"почему-то","answer":"због нечега", synonyms:[] },
        {"title":"потому,что","answer":"зато што", synonyms:[] },
        {"title":"зачем-то","answer":"због нечега", synonyms:[] },
        {"title":"и","answer":"и", synonyms:[] },
        {"title":"или","answer":"или", synonyms:[] },
        {"title":"но","answer":"али", synonyms:[] },
        {"title":"для(предлог)","answer":"за", synonyms:[] },
        {"title":"слишком","answer":"сувише", synonyms:[] },
        {"title":"только","answer":"само", synonyms:[] },
        {"title":"точно","answer":"тачно", synonyms:[] },
        {"title":"приблизительно","answer":"отприлике", synonyms:[] },
        {"title":"приблизительный","answer":"приближан", synonyms:[] },
        {"title":"почти","answer":"готово", synonyms:[] },
        {"title":"каждый","answer":"сваки", synonyms:[] },
        {"title":"любой","answer":"било који", synonyms:[] },
        {"title":"много","answer":"много", synonyms:[] },
        {"title":"многие","answer":"многи", synonyms:[] },
        {"title":"все(все люди)","answer":"сви", synonyms:[] },
        {"title":"в обмен на","answer":"у замену за", synonyms:[] },
        {"title":"взамен","answer":"у замену", synonyms:[] },
        {"title":"вручную","answer":"ручно", synonyms:[] },
        {"title":"вряд ли","answer":"једва да", synonyms:[] },
        {"title":"наверное(вероятно)","answer":"вероватно", synonyms:[] },
        {"title":"нарочно","answer":"намерно", synonyms:[] },
        {"title":"случайно","answer":"случајно", synonyms:[] },
        {"title":"очень","answer":"врло", synonyms:[] },
        {"title":"например","answer":"например", synonyms:[] },
        {"title":"между","answer":"између", synonyms:[] },
        {"title":"среди","answer":"међу", synonyms:[] },
        {"title":"столько","answer":"толико", synonyms:[] },
        {"title":"особенно","answer":"нарочито", synonyms:[] },
    ]
}

Serbian.Lesson5 = {
    LessonType : 'srb',
    Name : 'Геометрия',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"квадрат","answer":"квадрат", synonyms:[] },
        {"title":"квадратный","answer":"квадратан", synonyms:[] },
        {"title":"круг","answer":"круг", synonyms:[] },
        {"title":"круглый","answer":"округао", synonyms:[] },
        {"title":"треугольник","answer":"трокут", synonyms:[] },
        {"title":"треугольный","answer":"трокутан", synonyms:[] },
        {"title":"овал","answer":"овал", synonyms:[] },
        {"title":"овальный","answer":"овалан", synonyms:[] },
        {"title":"прямоугольник","answer":"правокутник", synonyms:[] },
        {"title":"прямоугольный","answer":"правокутан", synonyms:[] },
        {"title":"пирамида","answer":"пирамида", synonyms:[] },
        {"title":"ромб","answer":"ромб", synonyms:[] },
        {"title":"трапеция","answer":"трапез", synonyms:[] },
        {"title":"куб","answer":"куб", synonyms:[] },
        {"title":"призма","answer":"призма", synonyms:[] },
        {"title":"окружность","answer":"опсег", synonyms:[] },
        {"title":"сфера","answer":"сфера", synonyms:[] },
        {"title":"шар","answer":"кугла", synonyms:[] },
        {"title":"диаметр","answer":"пречник", synonyms:[] },
        {"title":"радиус","answer":"радијус", synonyms:[] },
        {"title":"периметр","answer":"периметар", synonyms:[] },
        {"title":"центр","answer":"центар", synonyms:[] },
        {"title":"горизонтальный","answer":"хоризонталан", synonyms:[] },
        {"title":"вертикальный","answer":"вертикалан", synonyms:[] },
        {"title":"параллель","answer":"паралела", synonyms:[] },
        {"title":"параллельный","answer":"паралелан", synonyms:[] },
        {"title":"линия","answer":"линија", synonyms:[] },
        {"title":"черта","answer":"црта", synonyms:[] },
        {"title":"прямая линия","answer":"права линија", synonyms:[] },
        {"title":"кривая линия","answer":"крива линија", synonyms:[] },
        {"title":"тонкий","answer":"танак", synonyms:[] },
        {"title":"контур","answer":"контура", synonyms:[] },
        {"title":"пересечение","answer":"пресек", synonyms:[] },
        {"title":"прямой угол","answer":"прави угао", synonyms:[] },
        {"title":"сегмент","answer":"сегмент", synonyms:[] },
        {"title":"сектор","answer":"одсек", synonyms:[] },
        {"title":"сторона","answer":"страна", synonyms:[] },
        {"title":"угол","answer":"угао", synonyms:[] },
        {"title":"вес","answer":"тежина", synonyms:[] },
        {"title":"длина","answer":"дужина", synonyms:[] },
        {"title":"ширина","answer":"ширина", synonyms:[] },
        {"title":"высота","answer":"висина", synonyms:[] },
        {"title":"глубина","answer":"дубина", synonyms:[] },
        {"title":"объём","answer":"обим", synonyms:[] },
        {"title":"площадь","answer":"површина", synonyms:[] },
        {"title":"грамм","answer":"грам", synonyms:[] },
        {"title":"миллиграмм","answer":"милиграм", synonyms:[] },
        {"title":"килограмм","answer":"килограм", synonyms:[] },
        {"title":"тонна","answer":"тона", synonyms:[] },
        {"title":"фунт(мера веса)","answer":"фунта", synonyms:[] },
        {"title":"унция","answer":"унца", synonyms:[] },
        {"title":"метр","answer":"метар", synonyms:[] },
        {"title":"миллиметр","answer":"милиметар", synonyms:[] },
        {"title":"сантиметр","answer":"сантиметар", synonyms:[] },
        {"title":"километр","answer":"километар", synonyms:[] },
        {"title":"миля","answer":"миља", synonyms:[] },
        {"title":"дюйм","answer":"палац", synonyms:[] },
        {"title":"фут","answer":"стопа", synonyms:[] },
        {"title":"ярд","answer":"јарда", synonyms:[] },
        {"title":"квадратный метр","answer":"квадратни метар", synonyms:[] },
        {"title":"гектар","answer":"хектар", synonyms:[] },
        {"title":"литр","answer":"литар", synonyms:[] },
        {"title":"градус","answer":"степен", synonyms:[] },
        {"title":"вольт","answer":"волт", synonyms:[] },
        {"title":"ампер","answer":"ампер", synonyms:[] },
        {"title":"лошадиная сила","answer":"коњска снага", synonyms:[] },
        {"title":"количество","answer":"количина", synonyms:[] },
        {"title":"штука","answer":"комад", synonyms:[] },
        {"title":"масштаб,размер(предмета)","answer":"размер", synonyms:[] },
        {"title":"минимальный","answer":"минималан", synonyms:[] },
        {"title":"наименьший","answer":"најмањи", synonyms:[] },
        {"title":"средний","answer":"средњи", synonyms:[] },
        {"title":"максимальный","answer":"максималан", synonyms:[] },
        {"title":"наибольший","answer":"највиши", synonyms:[] },
    ]
}


Serbian.Lesson6 = {
    LessonType : 'srb',
    Name : 'Материалы и сосуды',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"банка(стеклянная)","answer":"тегла", synonyms:[] },
        {"title":"банка(жестяная)","answer":"лименка", synonyms:[] },
        {"title":"ведро","answer":"ведро", synonyms:[] },
        {"title":"бочка","answer":"буре", synonyms:[] },
        {"title":"таз","answer":"лавор", synonyms:[] },
        {"title":"бак","answer":"котао", synonyms:[] },
        {"title":"фляжка","answer":"чутурица", synonyms:[] },
        {"title":"канистра","answer":"канта", synonyms:[] },
        {"title":"цистерна","answer":"цистерна", synonyms:[] },
        {"title":"кружка","answer":"кригла", synonyms:[] },
        {"title":"чашка","answer":"шоља", synonyms:[] },
        {"title":"блюдце","answer":"тацна", synonyms:[] },
        {"title":"бокал,стакан","answer":"чаша", synonyms:[] },
        {"title":"кастрюля","answer":"лонац", synonyms:[] },
        {"title":"бутылка","answer":"боца", synonyms:[] },
        {"title":"горлышко(бутылки)","answer":"грлић", synonyms:[] },
        {"title":"графин","answer":"стона боца", synonyms:[] },
        {"title":"кувшин","answer":"крчаг", synonyms:[] },
        {"title":"сосуд","answer":"суд", synonyms:[] },
        {"title":"горшок","answer":"крчак", synonyms:[] },
        {"title":"ваза","answer":"ваза", synonyms:[] },
        {"title":"флакон","answer":"флакон", synonyms:[] },
        {"title":"пузырёк","answer":"бочица", synonyms:[] },
        {"title":"тюбик","answer":"туба", synonyms:[] },
        {"title":"мешок(сахара и т.п.)","answer":"џак", synonyms:[] },
        {"title":"пакет(мешок)","answer":"кеса", synonyms:[] },
        {"title":"пачка(чая,сигарет)","answer":"пакло", synonyms:[] },
        {"title":"коробка","answer":"кутија", synonyms:[] },
        {"title":"ящик","answer":"сандуче", synonyms:[] },
        {"title":"корзина","answer":"корпа", synonyms:[] },
        {"title":"материал","answer":"материјал", synonyms:[] },
        {"title":"дерево","answer":"дрво", synonyms:[] },
        {"title":"деревянный","answer":"дрвен", synonyms:[] },
        {"title":"стекло","answer":"стакло", synonyms:[] },
        {"title":"стеклянный","answer":"стаклен", synonyms:[] },
        {"title":"каменный,камень","answer":"камен", synonyms:[] },
        {"title":"пластик,пластмасса","answer":"пластика", synonyms:[] },
        {"title":"пластмассовый","answer":"од пластике", synonyms:[] },
        {"title":"резина","answer":"гума", synonyms:[] },
        {"title":"резиновый","answer":"гумен", synonyms:[] },
        {"title":"ткань","answer":"тканина", synonyms:[] },
        {"title":"из ткани","answer":"од тканине", synonyms:[] },
        {"title":"бумага","answer":"папир", synonyms:[] },
        {"title":"бумажный","answer":"папиран", synonyms:[] },
        {"title":"картон","answer":"картон", synonyms:[] },
        {"title":"картонный","answer":"картонски", synonyms:[] },
        {"title":"полиэтилен","answer":"најлон", synonyms:[] },
        {"title":"целлофан","answer":"целофан", synonyms:[] },
        {"title":"фанера","answer":"шперплоча", synonyms:[] },
        {"title":"фарфор","answer":"порцулан", synonyms:[] },
        {"title":"фарфоровый","answer":"од порцелана", synonyms:[] },
        {"title":"глина","answer":"глина", synonyms:[] },
        {"title":"глиняный(о посуде)","answer":"земљан", synonyms:[] },
        {"title":"керамика","answer":"керамика", synonyms:[] },
        {"title":"керамический","answer":"керамички", synonyms:[] },
        {"title":"металл","answer":"метал", synonyms:[] },
        {"title":"металлический","answer":"металан", synonyms:[] },
        {"title":"сплав","answer":"слитина", synonyms:[] },
        {"title":"золото","answer":"злато", synonyms:[] },
        {"title":"серебро","answer":"сребро", synonyms:[] },
        {"title":"серебряный","answer":"сребрни", synonyms:[] },
        {"title":"железо","answer":"гвожђе", synonyms:[] },
        {"title":"железный","answer":"гвозден", synonyms:[] },
        {"title":"сталь","answer":"челик", synonyms:[] },
        {"title":"стальной","answer":"челичан", synonyms:[] },
        {"title":"медь","answer":"бакар", synonyms:[] },
        {"title":"медный","answer":"бакарни", synonyms:[] },
        {"title":"алюминий","answer":"алуминијум", synonyms:[] },
        {"title":"алюминиевый","answer":"алуминијумски", synonyms:[] },
        {"title":"бронза","answer":"бронза", synonyms:[] },
        {"title":"бронзовый","answer":"бронзан", synonyms:[] },
        {"title":"латунь","answer":"месинг", synonyms:[] },
        {"title":"никель","answer":"никл", synonyms:[] },
        {"title":"платина","answer":"платина", synonyms:[] },
        {"title":"ртуть","answer":"жива", synonyms:[] },
        {"title":"олово","answer":"калај", synonyms:[] },
        {"title":"свинец","answer":"олово", synonyms:[] },
        {"title":"цинк","answer":"цинк", synonyms:[] },
        {"title":"рай","answer":"рај", synonyms:[] },
        {"title":"ад","answer":"пакао", synonyms:[] },
    ]
}

Serbian.Lesson7 = {
    LessonType : 'srb',
    Name : 'Числа',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"ноль","answer":"нула", synonyms:[] },
        {"title":"один","answer":"један", synonyms:[] },
        {"title":"два","answer":"два", synonyms:[] },
        {"title":"три","answer":"три", synonyms:[] },
        {"title":"четыре","answer":"четири", synonyms:[] },
        {"title":"пять","answer":"пет", synonyms:[] },
        {"title":"шесть","answer":"шест", synonyms:[] },
        {"title":"семь","answer":"седам", synonyms:[] },
        {"title":"восемь","answer":"осам", synonyms:[] },
        {"title":"девять","answer":"девет", synonyms:[] },
        {"title":"десять","answer":"десет", synonyms:[] },
        {"title":"одиннадцать","answer":"једанаест", synonyms:[] },
        {"title":"двенадцать","answer":"дванаест", synonyms:[] },
        {"title":"тринадцать","answer":"тринаест", synonyms:[] },
        {"title":"четырнадцать","answer":"четрнаест", synonyms:[] },
        {"title":"пятнадцать","answer":"петнаест", synonyms:[] },
        {"title":"шестнадцать","answer":"шеснаест", synonyms:[] },
        {"title":"семнадцать","answer":"седамнаест", synonyms:[] },
        {"title":"восемнадцать","answer":"осамнаест", synonyms:[] },
        {"title":"девятнадцать","answer":"деветнаест", synonyms:[] },
        {"title":"двадцать","answer":"двадесет", synonyms:[] },
        {"title":"двадцать один","answer":"двадесет један", synonyms:["двадесет и један"] },
        {"title":"тридцать","answer":"тридесет", synonyms:[] },
        {"title":"сорок","answer":"четрдесет", synonyms:[] },
        {"title":"пятьдесят","answer":"педесет", synonyms:[] },
        {"title":"пятьдесят два","answer":"педесет два", synonyms:["педесет и два"] },
        {"title":"шестьдесят","answer":"шездесет", synonyms:[] },
        {"title":"семьдесят","answer":"седамдесет", synonyms:[] },
        {"title":"восемьдесят","answer":"осамдесет", synonyms:[] },
        {"title":"девяносто","answer":"деведесет", synonyms:[] },
        {"title":"девяносто три","answer":"деведесет три", synonyms:["деведесет и три"] },
        {"title":"сто","answer":"сто", synonyms:[] },
        {"title":"двести","answer":"двеста", synonyms:[] },
        {"title":"триста","answer":"триста", synonyms:[] },
        {"title":"четыреста","answer":"четиристо", synonyms:[] },
        {"title":"пятьсот","answer":"петсто", synonyms:[] },
        {"title":"шестьсот","answer":"шестсто", synonyms:[] },
        {"title":"семьсот","answer":"седамсто", synonyms:[] },
        {"title":"восемьсот","answer":"осамсто", synonyms:[] },
        {"title":"девятьсот","answer":"деветсто", synonyms:[] },
        {"title":"тысяча","answer":"хиљада", synonyms:[] },
        {"title":"две тысячи","answer":"две хиљаде", synonyms:[] },
        {"title":"три тысячи","answer":"три хиљаде", synonyms:[] },
        {"title":"десять тысяч","answer":"десет хиљада", synonyms:[] },
        {"title":"сто тысяч","answer":"сто хиљада", synonyms:[] },
        {"title":"миллион","answer":"милијун", synonyms:[] },
        {"title":"миллиард","answer":"милијарда", synonyms:[] },
        {"title":"первый","answer":"први", synonyms:[] },
        {"title":"второй","answer":"други", synonyms:[] },
        {"title":"третий","answer":"трећи", synonyms:[] },
        {"title":"четвёртый","answer":"четврти", synonyms:[] },
        {"title":"пятый","answer":"пети", synonyms:[] },
        {"title":"шестой","answer":"шести", synonyms:[] },
        {"title":"седьмой","answer":"седми", synonyms:[] },
        {"title":"восьмой","answer":"осми", synonyms:[] },
        {"title":"девятый","answer":"девети", synonyms:[] },
        {"title":"десятый","answer":"десети", synonyms:[] },
        {"title":"дробь","answer":"разломак", synonyms:[] },
        {"title":"одна вторая","answer":"једна половина", synonyms:[] },
        {"title":"одна третья","answer":"једна трећина", synonyms:[] },
        {"title":"одна четвертая","answer":"једна четвртина", synonyms:[] },
        {"title":"одна восьмая","answer":"једна осмина", synonyms:[] },
        {"title":"одна десятая","answer":"једна десетина", synonyms:[] },
        {"title":"две третьих","answer":"две трећине", synonyms:[] },
        {"title":"три четвёртых","answer":"три четвртине", synonyms:[] },
        {"title":"вычитание","answer":"одузимање", synonyms:[] },
        {"title":"вычитать","answer":"одузимати", synonyms:[] },
        {"title":"деление","answer":"делење", synonyms:[] },
        {"title":"делить","answer":"делити", synonyms:[] },
        {"title":"сложение","answer":"сабирање", synonyms:[] },
        {"title":"сложить","answer":"сабрати", synonyms:[] },
        {"title":"прибавлять","answer":"збрајати", synonyms:[] },
        {"title":"умножение","answer":"множење", synonyms:[] },
        {"title":"умножать","answer":"множити", synonyms:[] },
        {"title":"цифра,число,числительное","answer":"број", synonyms:[] },
        {"title":"минус","answer":"минус", synonyms:[] },
        {"title":"плюс","answer":"плус", synonyms:[] },
        {"title":"формула","answer":"формула", synonyms:[] },
        {"title":"вычисление","answer":"израчунавање", synonyms:[] },
        {"title":"считать","answer":"бројити", synonyms:[] },
        {"title":"подсчитывать","answer":"рачунати", synonyms:[] },
        {"title":"сумма","answer":"износ", synonyms:[] },
        {"title":"результат","answer":"резултат", synonyms:[] },
        {"title":"остаток","answer":"остатак", synonyms:[] },
        {"title":"несколько","answer":"неколико", synonyms:[] },
        {"title":"немного","answer":"мало", synonyms:[] },
        {"title":"остальное","answer":"остало", synonyms:[] },
        {"title":"полтора","answer":"један и по", synonyms:[] },
        {"title":"дюжина","answer":"туце", synonyms:[] },
        {"title":"пополам","answer":"попола", synonyms:[] },
        {"title":"поровну","answer":"равномерно", synonyms:[] },
        {"title":"половина","answer":"половина", synonyms:[] },
        {"title":"раз","answer":"пут", synonyms:[] },
    ]
}
Serbian.Lesson8 = {
    LessonType : 'srb',
    Name : 'Время',
    Directory : 'Сербский.Начало',
    Author : 'El Ege',
    Version : 1,
    Words : [
        {"title":"понедельник","answer":"понедељак", synonyms:[] },
        {"title":"вторник","answer":"уторак", synonyms:[] },
        {"title":"среда","answer":"среда", synonyms:[] },
        {"title":"четверг","answer":"четвртак", synonyms:[] },
        {"title":"пятница","answer":"петак", synonyms:[] },
        {"title":"суббота","answer":"субота", synonyms:[] },
        {"title":"воскресенье","answer":"недеља", synonyms:[] },
        {"title":"сегодня","answer":"данас", synonyms:[] },
        {"title":"завтра","answer":"сутра", synonyms:[] },
        {"title":"послезавтра","answer":"прекосутра", synonyms:[] },
        {"title":"вчера","answer":"јуче", synonyms:[] },
        {"title":"позавчера","answer":"прекјуче", synonyms:[] },
        {"title":"день","answer":"дан", synonyms:[] },
        {"title":"рабочий день","answer":"радни дан", synonyms:[] },
        {"title":"праздничный день","answer":"празничан дан", synonyms:[] },
        {"title":"выходной день","answer":"слободни дан", synonyms:[] },
        {"title":"выходные","answer":"викенд", synonyms:[] },
        {"title":"весь день","answer":"цео дан", synonyms:[] },
        {"title":"на следующий день","answer":"сутрадан", synonyms:[] },
        {"title":"два дня назад","answer":"пре два дана", synonyms:[] },
        {"title":"накануне","answer":"уочи", synonyms:[] },
        {"title":"ежедневный","answer":"свакодневни", synonyms:[] },
        {"title":"ежедневно","answer":"сваки дан", synonyms:[] },
        {"title":"неделя","answer":"недеља", synonyms:[] },
        {"title":"на прошлой неделе","answer":"прошле недеље", synonyms:[] },
        {"title":"на следующей неделе","answer":"идуће недеље", synonyms:[] },
        {"title":"еженедельный","answer":"недељни", synonyms:[] },
        {"title":"еженедельно","answer":"недељно", synonyms:[] },
        {"title":"два раза в неделю","answer":"два пута недељно", synonyms:[] },
        {"title":"каждый вторник","answer":"сваког уторка", synonyms:[] },
        {"title":"утро","answer":"јутро", synonyms:[] },
        {"title":"утром","answer":"ујутру", synonyms:[] },
        {"title":"полдень","answer":"подне", synonyms:[] },
        {"title":"после обеда","answer":"поподне", synonyms:[] },
        {"title":"вечер","answer":"вече", synonyms:[] },
        {"title":"вечером","answer":"увече", synonyms:[] },
        {"title":"ночь","answer":"ноћ", synonyms:[] },
        {"title":"ночью","answer":"ноћу", synonyms:[] },
        {"title":"полночь","answer":"поноћ", synonyms:[] },
        {"title":"час","answer":"сат", synonyms:[] },
        {"title":"полчаса","answer":"пола сата", synonyms:[] },
        {"title":"четверть часа","answer":"четврт сата", synonyms:[] },
        {"title":"пятнадцать минут","answer":"петнаест минута", synonyms:[] },
        {"title":"сутки","answer":"дан и ноћ", synonyms:[] },
        {"title":"восход солнца","answer":"излазак сунца", synonyms:[] },
        {"title":"рассвет","answer":"свануће", synonyms:[] },
        {"title":"раннее утро","answer":"рано ујутру", synonyms:[] },
        {"title":"закат","answer":"залазак сунца", synonyms:[] },
        {"title":"рано утром","answer":"рано ујутру", synonyms:[] },
        {"title":"сегодня утром","answer":"јутрос", synonyms:[] },
        {"title":"завтра утром","answer":"сутра ујутру", synonyms:[] },
        {"title":"сегодня после обеда","answer":"данас поподне", synonyms:[] },
        {"title":"завтра после обеда","answer":"сутра поподне", synonyms:[] },
        {"title":"сегодня вечером","answer":"вечерас", synonyms:[] },
        {"title":"завтра вечером","answer":"сутра увече", synonyms:[] },
        {"title":"ровно в три часа","answer":"у три сата тачно", synonyms:[] },
        {"title":"около четырёх часов","answer":"око четири сата", synonyms:[] },
        {"title":"к двенадцати часам","answer":"око дванаест сати", synonyms:[] },
        {"title":"через двадцать минут","answer":"кроз двадесет минута", synonyms:[] },
        {"title":"через час","answer":"кроз један сат", synonyms:[] },
        {"title":"вовремя","answer":"на време", synonyms:[] },
        {"title":"без четверти","answer":"четврт", synonyms:[] },
        {"title":"в течение часа","answer":"у току сат времена", synonyms:[] },
        {"title":"каждые пятнадцать минут","answer":"сваких петнаест минута", synonyms:[] },
        {"title":"круглые сутки","answer":"цео дан и ноћ", synonyms:[] },
        {"title":"январь","answer":"јануар", synonyms:[] },
        {"title":"февраль","answer":"фебруар", synonyms:[] },
        {"title":"март","answer":"март", synonyms:[] },
        {"title":"апрель","answer":"април", synonyms:[] },
        {"title":"май","answer":"мај", synonyms:[] },
        {"title":"июнь","answer":"јун", synonyms:[] },
        {"title":"июль","answer":"јули", synonyms:[] },
        {"title":"август","answer":"август", synonyms:[] },
        {"title":"сентябрь","answer":"септембар", synonyms:[] },
        {"title":"октябрь","answer":"октобар", synonyms:[] },
        {"title":"ноябрь","answer":"новембар", synonyms:[] },
        {"title":"декабрь","answer":"децембар", synonyms:[] },
        {"title":"весна","answer":"пролеће", synonyms:[] },
        {"title":"весной","answer":"у пролеће", synonyms:[] },
        {"title":"весенний","answer":"пролетни", synonyms:[] },
        {"title":"лето","answer":"лето", synonyms:[] },
        {"title":"летом","answer":"лети", synonyms:[] },
        {"title":"летний","answer":"летњи", synonyms:[] },
        {"title":"осень","answer":"јесен", synonyms:[] },
        {"title":"осенью","answer":"у јесен", synonyms:[] },
        {"title":"осенний","answer":"јесењи", synonyms:[] },
        {"title":"зима","answer":"зима", synonyms:[] },
        {"title":"зимой","answer":"зими", synonyms:[] },
        {"title":"зимний","answer":"зимски", synonyms:[] },
        {"title":"месяц","answer":"месец", synonyms:[] },
        {"title":"в этом месяце","answer":"овог месеца", synonyms:[] },
        {"title":"в следующем месяце","answer":"следећег месеца", synonyms:[] },
        {"title":"в прошлом месяце","answer":"прошлог месеца", synonyms:[] },
        {"title":"месяц назад","answer":"пре месец дана", synonyms:[] },
        {"title":"через месяц","answer":"за месец дана", synonyms:[] },
        {"title":"через два месяца","answer":"за два месеца", synonyms:[] },
        {"title":"весь месяц","answer":"сав месец", synonyms:[] },
        {"title":"целый месяц","answer":"цео месец", synonyms:[] },
        {"title":"ежемесячный","answer":"месечни", synonyms:[] },
        {"title":"ежемесячно","answer":"месечно", synonyms:[] },
        {"title":"каждый месяц","answer":"сваки месец", synonyms:[] },
        {"title":"два раза в месяц","answer":"два пута месечно", synonyms:[] },
        {"title":"год","answer":"година", synonyms:[] },
        {"title":"в этом году","answer":"ове године", synonyms:[] },
        {"title":"в следующем году","answer":"идуће године", synonyms:[] },
        {"title":"год назад","answer":"пре годину дана", synonyms:[] },
        {"title":"через год","answer":"преко године", synonyms:[] },
        {"title":"через два года","answer":"кроз две године", synonyms:[] },
        {"title":"весь год","answer":"цела година", synonyms:[] },
        {"title":"целый год","answer":"целу годину", synonyms:[] },
        {"title":"каждый год","answer":"сваку годину", synonyms:[] },
        {"title":"ежегодный","answer":"годишњи", synonyms:[] },
        {"title":"ежегодно","answer":"годишње", synonyms:[] },
        {"title":"четыре раза в год","answer":"четири пута годишње", synonyms:[] },
        {"title":"дата,число","answer":"датум", synonyms:[] },
        {"title":"календарь","answer":"календар", synonyms:[] },
        {"title":"полгода","answer":"пола године", synonyms:[] },
        {"title":"полугодие","answer":"полугодиште", synonyms:[] },
        {"title":"сезон","answer":"сезон", synonyms:[] },
        {"title":"век","answer":"век", synonyms:[] },
        {"title":"время","answer":"време", synonyms:[] },
        {"title":"миг","answer":"часак", synonyms:[] },
        {"title":"мгновение","answer":"тренутак", synonyms:[] },
        {"title":"мгновенный","answer":"тренутан", synonyms:[] },
        {"title":"отрезок времени","answer":"раздобље", synonyms:[] },
        {"title":"жизнь","answer":"живот", synonyms:[] },
        {"title":"вечность","answer":"вечност", synonyms:[] },
        {"title":"эпоха","answer":"доба", synonyms:[] },
        {"title":"эра","answer":"ера", synonyms:[] },
        {"title":"цикл","answer":"циклус", synonyms:[] },
        {"title":"период","answer":"период", synonyms:[] },
        {"title":"срок(долгий~)","answer":"рок", synonyms:[] },
        {"title":"будущее","answer":"будућност", synonyms:[] },
        {"title":"будущий","answer":"будући", synonyms:[] },
        {"title":"в следующий раз","answer":"следећи пут", synonyms:[] },
        {"title":"прошлое","answer":"прошлост", synonyms:[] },
        {"title":"прошлый","answer":"прошли", synonyms:[] },
        {"title":"в прошлый раз","answer":"прошлог пута", synonyms:[] },
        {"title":"позже","answer":"касније", synonyms:[] },
        {"title":"после","answer":"после", synonyms:[] },
        {"title":"сейчас, в эту минуту, в наше время","answer":"сада", synonyms:[] },
        {"title":"немедленно","answer":"одмах", synonyms:[] },
        {"title":"скоро","answer":"ускоро", synonyms:[] },
        {"title":"заранее","answer":"унапред", synonyms:[] },
        {"title":"давно","answer":"одавно", synonyms:[] },
        {"title":"недавно","answer":"недавно", synonyms:[] },
        {"title":"судьба","answer":"судбина", synonyms:[] },
        {"title":"память, воспоминания","answer":"памћење", synonyms:[] },
        {"title":"архив","answer":"архив", synonyms:[] },
        {"title":"во время","answer":"за време", synonyms:[] },
        {"title":"долго","answer":"дуго", synonyms:[] },
        {"title":"недолго","answer":"кратко", synonyms:[] },
        {"title":"рано","answer":"рано", synonyms:[] },
        {"title":"поздно","answer":"касно", synonyms:[] },
        {"title":"навсегда","answer":"заувек", synonyms:[] },
        {"title":"перенести срок","answer":"одложити", synonyms:[] },
        {"title":"одновременно","answer":"истовремено", synonyms:[] },
        {"title":"постоянно","answer":"стално", synonyms:[] },
        {"title":"постоянный","answer":"сталан", synonyms:[] },
        {"title":"временный","answer":"повремен", synonyms:[] },
        {"title":"иногда","answer":"понекад", synonyms:[] },
        {"title":"редко","answer":"ретко", synonyms:[] },
    ]
}
